### ISSUE TITLE
Error loading devtools in Vue 2

### ISSUE THREAD

**Issue by stellR42** [DamianOsipiuk/vue-query#101]
When trying to load devtools, I get this error:
`export resolveComponent (imported as 'VueDemi') was not found in 'vue-demi'`
Versions:
vue: 2.6.12,
vue-demi: 0.12.1,
vue-query: 1.15.0

**Comment by DamianOsipiuk** [comment]
Hi, could you try downgrading vue-demi to 0.10.1?
If that helps i would need to pin the package version.

**Comment by DamianOsipiuk** [comment]
@stellR42 Could you try with https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.18.1

**Comment by DamianOsipiuk** [comment]
Fell free to reopen this ticket if it still does not work
