### ISSUE TITLE
Types break when using reactive in options

### ISSUE THREAD

**Issue by andresespinosapc** [DamianOsipiuk/vue-query#106]
I have this in a query:
```javascript
return useInfiniteQuery<ProductQueryFn, APIError>(
  queryKey,
  queryFn,
  {
    getNextPageParam: ({ pagy: { next: nextPage } }) => ((nextPage === null) ? undefined : nextPage),
  },
);
```

But when I try to turn options into reactive, typescript stops recognizing the type of the params of `getNextPageParam`. This is the code where it doesn't work:

```javascript
return useInfiniteQuery<ProductQueryFn, APIError>(
  queryKey,
  queryFn,
  reactive({
    enabled: computed(() => true),
    getNextPageParam: ({ pagy: { next: nextPage } }) => ((nextPage === null) ? undefined : nextPage),
  }),
);
```

**Comment by DamianOsipiuk** [comment]
This PR should fix the issue, as you would not need `reactive` wrapper for options anymore: https://github.com/DamianOsipiuk/vue-query/pull/111

**Comment by DamianOsipiuk** [comment]
@andresespinosapc You could try https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.18.0 where you do not need `reactive` wrapper around options anymore.
In case of any problems feel free to reopen the ticket.
