### ISSUE TITLE
[Bug Report] 'Error: Dynamic require of "vue-demi" is not supported' when trying to add VueQueryDevTools to vue3 

### ISSUE THREAD

**Issue by userProfileIsAvailable** [DamianOsipiuk/vue-query#127]
when trying to add VueQueryDevTools to the vue3 project, console report error [ Dynamic require of "vue-demi" is not supported]

**Comment by userProfileIsAvailable** [comment]
@DamianOsipiuk repo-link: https://github.com/userProfileIsAvailable/vitesse-lite-sass
bug reproduction: 
-run pnpm i
-npm run dev

**Comment by DamianOsipiuk** [comment]
I have checked it and was unable to reproduce the issue.

Could you try to remove `node_modules` and reinstall packages?
Also try running `npx vue-demi-fix`

**Comment by userProfileIsAvailable** [comment]
thanks for your help , after switching vite version to 2.6.14, the issue didn't show up
