### ISSUE TITLE
Error with vue2:  export 'toRefs' (imported as 'toRefs') was not found in 'vue-demi'

### ISSUE THREAD

**Issue by scil** [DamianOsipiuk/vue-query#128]
my sollution: `npm i @vue/composition-api`

**Comment by DamianOsipiuk** [comment]
@scil This is not a bug. Vue 2 users have to install `composition-api` as it's a peer dependency that is not needed in vue3.
As mentioned in docs: `Vue Query is compatible with Vue 2.x + composition API or 3.x`.

You might want to check the `Vue2` example for a proper project setup: https://github.com/DamianOsipiuk/vue-query/tree/main/examples/2.x-basic

**Comment by scil** [comment]
> @scil This is not a bug. Vue 2 users have to install `composition-api` as it's a peer dependency that is not needed in vue3. As mentioned in docs: `Vue Query is compatible with Vue 2.x + composition API or 3.x`.
> 
> You might want to check the `Vue2` example for a proper project setup: https://github.com/DamianOsipiuk/vue-query/tree/main/examples/2.x-basic

I not mention it as a bug. I just think the doc not clear enough. 

with vue2, I ` npm install vue-query  @vue/composition-api`   
then 
```
import { VueQueryPlugin } from "vue-query";
import { VueQueryDevTools } from "vue-query/devtools";
Vue.use(VueQueryPlugin);
```

But I do not know how to do next to use vue-query in a html page.  Is there any example to use vue-query with vue2?
