### ISSUE TITLE
how to use vue-query with vue2 in a html page? 

### ISSUE THREAD

**Issue by scil** [DamianOsipiuk/vue-query#129]
with vue2, I ` npm install vue-query  @vue/composition-api`   
then 
```
import { VueQueryPlugin } from "vue-query";
import { VueQueryDevTools } from "vue-query/devtools";
Vue.use(VueQueryPlugin);
```

But I do not know how to do next to use vue-query in a html page.  Is there any example to use vue-query in this app?
```
var appBoard = new Vue({
      el: '#board',
      data:function () {
        return {
          layout: my_fetch('xxx'),
        }
      }
  })
```

**Comment by DamianOsipiuk** [comment]
Check following example: https://github.com/DamianOsipiuk/vue-query/tree/main/examples/2.x-basic
Relevant pieces:
- https://github.com/DamianOsipiuk/vue-query/blob/main/examples/2.x-basic/src/main.ts (app setup)
- https://github.com/DamianOsipiuk/vue-query/blob/main/examples/2.x-basic/src/Posts.vue (query usage)
