### ISSUE TITLE
Objects with `value` key breaks vue-query dev tools on nuxt 2

### ISSUE THREAD

**Issue by achaphiv** [DamianOsipiuk/vue-query#131]
Reproduction: 

- Go to: https://codesandbox.io/s/patient-wave-kwyg2v?file=/pages/index.vue
- Open the vue-query dev tools
- Click `["todos"]`
- Notice error on page

In chrome, the error is:

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '__ob__' -> object with constructor 'Observer'
    --- property 'value' closes the circle
```

In firefox:

```
TypeError: cyclic object value
```

The only change I made was the third line:

```js
  await fetch("https://jsonplaceholder.typicode.com/todos")
    .then((response) => response.json())
    // The only change
    .then((it) => ({ value: it }))
```

I noticed this issue because a response had a `value` key.

As a side note, this sandbox also shows the error from #101.

**Comment by DamianOsipiuk** [comment]
@achaphiv Fixed in https://github.com/DamianOsipiuk/vue-query/pull/134
https://codesandbox.io/s/gracious-forest-gb0pub
