### ISSUE TITLE
Request on mounted

### ISSUE THREAD

**Issue by enyelsequeira** [DamianOsipiuk/vue-query#136]
I am working on a movie app and wanted to fetch all the information about the specific movie by id  ie: url/movie/[id] when I go to this page the first time it works well, but the second I refresh I get undefined, I've also tried putting this on the onMouted function and still same error. I'll share some of the code I've tried. I tried putting it the hook outside as well

![CleanShot 2022-03-08 at 17 54 30](https://user-images.githubusercontent.com/50872387/157212531-5d7057f4-b8e1-42c5-a4d9-5895e2d763e8.png)

**Comment by shoaibsharif** [comment]
In `useQuery` you should use the options called `enabled`. You shouldn't use `useQuery` inside the `mounted` hook as we don't know when it will fetch or how long it will take to fetch a query. I think what you could do:

```js
const id;
const {data}  = useQuery("movie",  moviefetcher, {enabled: Boolean(id)})

onMounted(() => {
   id = 1
})

```

**Comment by DamianOsipiuk** [comment]
If your problem is not solved feel free to reopen the issue.
