### ISSUE TITLE
[BUG] in vue/vueQueryPlugin.d.ts type error in vuejs 2

### ISSUE THREAD

**Issue by joojaewoo** [DamianOsipiuk/vue-query#146]
I use vue-query in project

```
    // package.json
    "vue": "2.6.11",
    "vue-query": "^1.19.2",
    "@vue/composition-api": "1.4.9",
```

I want to build with vue-cli, but type error occurred.

my build command is `vue-cli-service build`

Type errors still occur in your example 2.x-basic.
No error when using vite.

Do you check this issue? 
I'm attaching the picture below.

![image](https://user-images.githubusercontent.com/46195613/158340516-c8dd0acb-3016-4a75-bcfa-f68231e031ec.png)

**Comment by leedabin** [comment]
I am having the same problem.

I wish it was modified to support both useQueryProvider and VueQueryPlugin.

**Comment by joojaewoo** [comment]
VueQueryDevTools have same problem.

ERROR in .../vue-query/lib/devtools/DevtoolsPanel.vue.d.ts(9,44):
'vue-demi/lib/index' has no exported member 'DefineComponent'
```
declare const _default: import("vue-demi").DefineComponent<{
```

Build cannot proceed because of an error.
I wish check this problem.

**Comment by wobsoriano** [comment]
I have some libraries using vue-demi too, it’s the culprit

**Comment by DamianOsipiuk** [comment]
@joojaewoo Vue3-only type import from vueQueryPlugin will be removed in https://github.com/DamianOsipiuk/vue-query/pull/147

As for the DevTools, for now i do not have a fix for it.
You might want to set `skipLibCheck: true` in your tsconfig for now.
