### ISSUE TITLE
setQueryData() not updating dependent components

### ISSUE THREAD

**Issue by henry-chris** [DamianOsipiuk/vue-query#148]
In the following, when `PauseSubscriptionMutation` is called I attempt to update some properties on the `accountSummary` query if it's successful.

When I do `return { ...oldResponse }` I would expect Vue to understand that there is new data in the `accountSummary` query and to update each dependent component (Component 1).

That is not the case.  `isSubscribed` should compute again as it's dependent on `data.value` from the query, but it does not.

However, if I set that line to `return {}` then Component 1 does update (even though nothing exists in the object).

Am I way off base here?  What is the correct way to do this?

**Component 1:**

```
<template>
 <div v-if="isSubscribed">
     Yayyy!!
  </div>
</template>

<script setup lang="ts">
const { isLoading, data } = useAccountSummaryQuery();

// This will need to change when there are more subscriptions
const isSubscribed= computed(() => {
  const subscriptions = data.value?.subscriptions;
  return subscriptions.isSubscribed
}
</script>
```

**Queries:**

```
export function useAccountSummaryQuery() {
  return useQuery(
    ['accountSummary'],
    () => axios.get('/account/summary') as Promise<AxiosResponse<GetAccountSummaryResponse>>,
    {
      staleTime: 60 * 1000,
      select: (response) => response.data,
    }
  )
}

export function usePauseSubscriptionMutation() {
  const client = useQueryClient()
  return useMutation((subscriptionId: string | undefined) => axios.post(`/subscriptions/${subscriptionId}/pause`) as Promise<AxiosResponse<Subscription>>,
  {
    onSuccess: (newResponse, variables, context) => {
      client.setQueryData('accountSummary', (old) => {
         const oldResponse = old as AxiosResponse<GetAccountSummaryResponse>

         oldResponse.data.subscriptions = oldResponse.data.subscriptions.map(s => 
           s.subscriptionId === newResponse.data.subscriptionId
            ? mapSubscriptionToAccountSummarySubscription(s, newResponse.data)
            : s
         )

         return { ...oldResponse }  // The line in question
      })
    }
  })
}
```

**Comment by DamianOsipiuk** [comment]
Hi @henry-chris,

Could you check in devtools, if your data is being updated in the cache?
If no, then maybe this query is in fetching state at the same time, and it's overwriting your changes.
```ts
onSuccess: async () => {
  // Cancel any outgoing refetches (so they don't overwrite our optimistic update)
  await queryClient.cancelQueries('accountSummary')
}
```

If it's changed in the cache, but not updated in UI, then maybe you need to add a `watch` to check for changes in data.

**Comment by henry-chris** [comment]
Adding a `CancelQueries` does not help and I can verify it is not fetching new state.  It fetches at app creation and doesn't fetch again for at least a minute.

I added an `onSuccess` that **logs out the response** from the `accountSummary` query.  When the mutation is called that uses `setQueryData('accountSummary')` and I return `return { ...oldResponse }`:

I get 3-5 log statements from the `accountSummary` `onSuccess` method.  The log statements contain the updated state of the data.

However, the component using the query does not seem to think that `data` has changed.

I would expect that if a successful query happens then `data` would automatically trigger a change if it's a completely new object.

If in the `setQueryData()` method I instead return something like: 

 ```
return { 
    ...oldResponse,
    data: {...oldResponse.data, updatedQuery: Date.now() },
}
```

then the component registers the change correctly every time (obviously).  Note that I have to spread both the root response object (`oldresponse`) **and** change a root `data` property or else I don't see the change effect my component.

Even `return { ...oldResponse, updatedQuery: Date.now() } doesn't update my component.

So, I question how it's computing a **change** at the moment.

**Comment by DamianOsipiuk** [comment]
Could you check if new data is reflected in `VueQueryDevTools `? If that is the case then this is due to how vue reactivity works, not the library core.
It would be easier then to pinpoint if this could be fixed in the library itself, or in the userspace as a best-practise.

**Comment by henry-chris** [comment]
Apologies, yes.  

I boot up my app and devtools looks like so (i've removed all queries but the one in question)

![image](https://user-images.githubusercontent.com/4165721/159097616-52458038-e8d3-4ea7-b677-73b2e0d05ed7.png)

I wait a bit and then press a button which activates the mutation and set the query data and it looks like so:

![image](https://user-images.githubusercontent.com/4165721/159097647-ea02cff7-d1eb-4b9e-92d3-f37fbf37820f.png)

So, it definitely says that's it's updated exactly when the mutation happens...and the data is updated in the object correctly.

So, I guess that means it's up to Vue reactivity?

**Comment by henry-chris** [comment]
Question: Is there any reason to use the full Axios response?

For example:  

![image](https://user-images.githubusercontent.com/4165721/159100798-1310ea3c-b731-4e38-88d8-32d352e352f0.png)

Vs something silly like this:

![image](https://user-images.githubusercontent.com/4165721/159100820-4b18b159-bb57-49d0-aea1-2d3f88ed6927.png)


Keeping only the data object seems to make it easier for Vue to see changes and negates the need for a `select`

**Comment by DamianOsipiuk** [comment]
Definitely you should return data only from the fetcher function, instead of the whole response object.

Additionally i think what is happening is that you are updating some nested value in your data. Vue reactivity will see that `data` in your case is actually the same, so there is no need to update.

You could try returning actual data from fetcher function and then creating new object in `setQueryData`.
If that does not help you would need to use `watch` function from Vue to watch for deeply nested changes.

I would rather avoid setting a `ref` in the cache.

**Comment by henry-chris** [comment]
That's definitely the reason why (deeply nested).  The problem is that setting a new object with spread just doesn't trigger a change.  It seems you have to actually change something in a top level property.

So, as far as I can tell I would need multiple watchers which starts to defeat the purpose and is starting to get into full blow 'store' territory.

For an array, if I add or remove an object from the array it recognizes it...but if I just change an item in the array does not seem to recognize a change.

Since api mutations happen so infrequently I'm looking for the simplest way to say `Notify all dependents when mutated` because I'm not interested in fighting with Vue/vue-query to make sure 10 deeply nested objects/arrays are all appropriately watched individually.

For now, sadly, that fix is setting it as a `ref` in `setQueryData` until that proves to not work. So far it works in 100% of the cases I need it to work.

I can close this  as I don't think it's specifically Vue-query that I'm having the issue with...but coming from React it does seem like it should simply work by setting a new object.

**Comment by DamianOsipiuk** [comment]
@henry-chris So i have played for a second with it and it is as follows:
- in you mutate function, you are executing side-effect to change data in existing cache
- in your side effect you are changing deeply nested parameter value
- you return the same old object with deeply changed value
- you listen for a reactive change in actual component

The reason that it does not work is actually that by changing the nested property you also change the `value` in the reactive object itself. So when update happens it looks for `old` and `new` value that are actually the same, case you have mutated the object on which the reactivity has a reference.
Since `old` and `new` object along the path to the changed value are the same, they satisfy shallow compare for object equality and bail out of checking deeper (objRef === objRef).

I think the proper solution here would be to clone the object first and modify it as you see fit:

```ts
onSuccess: (newResponse, variables, context) => {
  client.setQueryData('accountSummary', (oldData) => {
     const newData= cloneDeep(oldData)

     newData.subscriptions = newData.subscriptions.map(s => 
       s.subscriptionId === newResponse.data.subscriptionId
        ? mapSubscriptionToAccountSummarySubscription(s, newResponse.data)
        : s
     )

     return newData;
  })
}
```

So the only addition you need to make is to get `cloneDeep` function from somewhere and everything should start working as intended.

**Comment by henry-chris** [comment]
I appreciate the help.  I will go ahead and do that then.

I guess I've worked with deeply nested objects before in other projects and have not come across this problem (Not using Vue).  So, it perplexed me.

Again, thanks for taking the time. I probably should have known I would need to deep clone or something similar.

Closing.

**Comment by DamianOsipiuk** [comment]
Do not worry. Vue reactivity is a bit tricky at times.
I scrached my head on several occasions when writing this library. 😉
