### ISSUE TITLE
watch not working on data ref

### ISSUE THREAD

**Issue by kouts** [DamianOsipiuk/vue-query#151]
First of all, thank you for your great work in this library. I encountered an issue when replacing [useAsyncState](https://vueuse.org/core/useAsyncState/) with `useQuery` in my project. It seems that the data ref cannot be `watch`ed, i.e the watcher doesn't respond when data is fetched from the API. As a result `useStorage` from vue-use does not work on `vue-query` data.

I've prepared a [codesandbox that demonstrates the issue here](https://codesandbox.io/s/vue-query-reactivity-cb9en4?file=/src/store.js).
When you select a user from the users' list you'll notice that although the user data gets updated, the watcher (which is setup inside `store.js`) does not fire. When you replace `useQuery` with `useAsyncState` inside the `Users.vue` file, the watcher fires as expected.
I've also tried the same thing with [swrv](https://github.com/Kong/swrv) and the watcher fires as expected as well.

Watch not working with `vue-query`
![watch-not-working](https://user-images.githubusercontent.com/2233663/160228984-6828a254-1921-445d-a5f3-6c52aac60230.gif)

Watch working with `vue-use` `useAsyncState`
![watch-working](https://user-images.githubusercontent.com/2233663/160228992-3213dd50-406e-4783-89ff-b4136dab0829.gif)

**Comment by wobsoriano** [comment]
What are you trying to do with the watched ref inside the pinia store?

**Comment by kouts** [comment]
I'm trying to sync it with `localStorage`

**Comment by wobsoriano** [comment]
Not sure if vue-query has this but it's experimental https://react-query.tanstack.com/plugins/persistQueryClient

**Comment by kouts** [comment]
After digging a bit I found that the issue is caused by `readonly` here https://github.com/DamianOsipiuk/vue-query/blob/c13a1e353da7ffe869c84ae1b00e302fdf0daf1c/src/vue/useBaseQuery.ts#L79

**Comment by wobsoriano** [comment]
Ah yes the readonly wrap can be removed there I think

**Comment by kouts** [comment]
I think this is an issue with Pinia not being able to track changes on the data object if the data object comes from an object that was wrapped with `readonly`.
I have created an issue in the Pinia repo https://github.com/vuejs/pinia/issues/1175

If `readonly` is actually not needed in `useBaseQuery.ts` maybe it would be a good idea to remove it anyway, @DamianOsipiuk WDYT?

**Comment by DamianOsipiuk** [comment]
Interesting.
I would rather not remove `readonly`, since it will open the door to state mutation, which is actually a bad thing as it might break reactivity in unexpected ways. Immutability of returned data is actually expected.
Maybe adding `readonly` after converting to refs would help here?

**Comment by kouts** [comment]
`readonly` makes sense @DamianOsipiuk, thanks, closing this as a workaround has been found in https://github.com/vuejs/pinia/issues/1175

**Comment by DHFW** [comment]
@kouts can you explain what the workaround is?

The `watch` on my query data only fires the first time when the data is fetched. The second time the data is available in the template, but the watch is not firing (coming from the cache).
My workaround now is to set the `cacheTime` of that query to 0 so it ignores the cache, but that is not a real solution.

**Comment by Holi0317** [comment]
I am not sure if this is related. But this might help others when searching similar issue.

The problem I faced was watcher for `query.data` was not fired when the query did update, but the data is still the same (didn't change on the sever side). The watcher is fired if the data is changed.

I was solving this by watching `query.dataUpdatedAt` instead, which will change whenever the query got refreshed.

**Comment by Mosaab-Emam** [comment]
Thanks @Holi0317, watching `dataUpdatedAt` fixed it for me.
