### ISSUE TITLE
seems useQuery doesn't work in <script setup>

### ISSUE THREAD

**Issue by gezichenshan** [DamianOsipiuk/vue-query#156]
```
<script setup lang="ts">
const props = defineProps({
  country: {
    type: String,
    required: true,
  },
})
const { data, refetch } = useQuery(["UNIVERSITY", props.country], () =>
  getUniversities(props.country),
)
```
This is my List.vue component which accept a `country` as its prop.
But when the contry prop changed outside, the useQuery in List.vue doesn't fire a request.

**Comment by gezichenshan** [comment]
```
<script lang="ts">
import { useQuery, useQueryClient } from "vue-query"
import { getUniversities } from "@/services/api"
export default {
  components: { listItem },
  props: {
    country: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    const { data, refetch } = useQuery(["UNIVERSITY", props.country], () =>
      getUniversities(props.country),
    )

    return { data }
  },
}
</script>
```
this embeded style setup doesn't fire a request either.

**Comment by gezichenshan** [comment]
In fact, I just want to know how the cache works.
If I do refetch mannually, the cache seems doesn't work. 
I tried many method like add initialData: queryClient.getQueryData("UNIVERSITY")?.find((d) => d.id === props.country); no matters.

**Comment by DamianOsipiuk** [comment]
Hi @gezichenshan 
I think props in vue are `reactive`, not refs. Therefore when they are placed directly in the queryKey array, reactivity is lost.

You could try:
```js
useQuery(["UNIVERSITY", {country: props.country}], ...)
```

or

```js
const countryKey = computed(() => props.country)
useQuery(["UNIVERSITY", countryKey], ...)
```

**Comment by gezichenshan** [comment]
@DamianOsipiuk  Thanks for you reply!

The second method works.

But I don't know why the result is not cached (it will refetch though the cache key ["UNIVERSITY", countryKey] keeps the same) when I change the props.country

**Comment by DamianOsipiuk** [comment]
I think you would have to provide some minimal reproduction repo, cause basic example seems to work fine. I'm not sure what is the problem.
As for cache, please use DevTools to check what is cached and when - https://vue-query.vercel.app/#/getting-started/devtools?id=floating-mode.
Please also read about the default settings https://vue-query.vercel.app/#/guides/important-defaults

**Comment by gezichenshan** [comment]
@DamianOsipiuk  Hi, I created a sample: https://codesandbox.io/s/intelligent-tharp-xiydnf?file=/src/components/Son.vue:138-248

If I understand correctly, the fetcher in Son.vue will not be fired if the cache key has ever been used?

**Comment by DamianOsipiuk** [comment]
I strongly reccomend to read https://vue-query.vercel.app/#/guides/important-defaults

`Query instances via useQuery or useInfiniteQuery by default consider cached data as stale`

It means that when you have data in cache it will be presented to the user immidiately, but also refetched in the background, and updated on the screen if there is a difference.
You can change this behavior by modifying `staleTime`.

**Comment by DamianOsipiuk** [comment]
In case you have more questions about this, feel free to reopen the issue
