### ISSUE TITLE
v1.22.0 jest tests fail

### ISSUE THREAD

**Issue by kouts** [DamianOsipiuk/vue-query#160]
After updating to v1.22.0 we have jest tests failing in our app with:
`ReferenceError: __VUE_PROD_DEVTOOLS__ is not defined`

As a workaround, we added
`__VUE_PROD_DEVTOOLS__: false,`
to `jest.globals`

If this is intentional maybe it's a good idea to add it to the docs.

**Comment by DamianOsipiuk** [comment]
Fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.22.1

**Comment by kouts** [comment]
Thanks for your efforts @DamianOsipiuk
