### ISSUE TITLE
Error Typescript typing "queryClient.setQueryData"

### ISSUE THREAD

**Issue by Pandazaur** [DamianOsipiuk/vue-query#166]
Hello I'm trying to use a `queryClient.setQueryData` in Typescript but I'm encountering an error on the second argument.

My code: 
```typescript
queryClient.setQueryData<QueryType>(queryKey, (oldApplyData) => {
    return oldApplyData
})
```

`QueryType` = the response type used in the query using the `queryKey` key

The error:
```
Argument of type '(oldApplyData: QueryType | undefined) => QueryType | undefined' is not assignable to parameter of type 'Updater<QueryType | undefined, QueryType>'.
  Type '(oldApplyData: QueryType | undefined) => QueryType | undefined' is not assignable to type 'DataUpdateFunction<QueryType | undefined, QueryType>'.
```

I followed the guide [https://vue-query.vercel.app/#/guides/mutations]() but nothing is about the typescript usage.

How can I type my second argument ?

**Comment by DamianOsipiuk** [comment]
In case you have more questions about this, feel free to reopen the issue

**Comment by andrewvasilchuk** [comment]
Having the same issue
