### ISSUE TITLE
suggestion: refetch/remove unrefd

### ISSUE THREAD

**Issue by marina-mosti** [DamianOsipiuk/vue-query#174]
Thansk for the great lib ^-^!
Minor suggestion ~

Currently at: 

https://github.com/DamianOsipiuk/vue-query/blob/098d08b50d13e44c77b56981ec79b8934d23fb98/src/vue/useBaseQuery.ts#L79

it looks like everything is getting `toRefs`, maybe it would be a nice idea to skip out on reffing `refetch` and `remove` from the reactivity pool since they are both functions.

It makes up for an unusal way to call them.
`const query = useQuery({})`
`query.refetch.value()` vs `query.fetch()`

From the useQuery docs:
```
refetch: (options: { throwOnError: boolean, cancelRefetch: boolean }) => Promise<UseQueryResult>

    A function to manually refetch the query.
    If the query errors, the error will only be logged. If you want an error to be thrown, pass the throwOnError: true option
    If cancelRefetch is true, then the current request will be cancelled before a new request is made

remove: () => void

    A function to remove the query from the cache.
```

**Comment by DamianOsipiuk** [comment]
Thanks for suggestion.
It's already planned for v2 to avoid breaking changes.
https://github.com/DamianOsipiuk/vue-query/issues/124

**Comment by marina-mosti** [comment]
Awesome looking forward
