### ISSUE TITLE
Share cache between separate apps?

### ISSUE THREAD

**Issue by avatarbabe** [DamianOsipiuk/vue-query#177]
Maybe I've missed something in the docs, but I can't seem to find anything similar to React-query's QueryClientProvider with contextSharing set to true. My frontend application is split up into several small vue-apps, and I would like to share the query cache between them. Registering the plugin in the main file of the separate apps doesn't allow them to share their cache. Is there a way to make them use the same cache?

**Comment by DamianOsipiuk** [comment]
Hi, i think this is currently a missing feature.
It shouldn't be too hard to add though.
