### ISSUE TITLE
Nuxt 3 error : Directory import react-query core is not supported resolving ES modules

### ISSUE THREAD

**Issue by Hebilicious** [DamianOsipiuk/vue-query#180]
Hello, I'm trying to migrate an app to Nuxt 3 and I'm encountering this error while running `nuxt generate` : 
I know the support is experimental at this stage, and I'm unsure if this is a Nuxt issue or a Vue query issue. 

The pre-rendering server is doing something like this :

```js
import * as core from 'react-query/core';

// core is then referenced many times like this :

function useQuery(arg1, arg2, arg3) {
	  return useBaseQuery(core.QueryObserver, arg1, arg2, arg3);
}
```

If I remove `react-query` from my dependencies, I get a different error 

```
[nuxt] [request error] Cannot find package 'react-query' imported from
```

 Here's the full Error with react-query in the deps
```
[nuxt] [request error] Directory import 'website-nuxt/node_modules/react-query/core' is not supported resolving ES modules imported from website-nuxt/.nuxt/prerender/chunks/app/server.mjs
Did you mean to import react-query@3.38.0/node_modules/react-query/lib/core/index.js?
  at new NodeError (node:internal/errors:372:5)  
  at finalizeResolution (node:internal/modules/esm/resolve:401:17)  
  at moduleResolve (node:internal/modules/esm/resolve:964:10)  
  at defaultResolve (node:internal/modules/esm/resolve:1173:11)  
  at ESMLoader.resolve (node:internal/modules/esm/loader:604:30)  
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)  
  at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:80:40)  
  at link (node:internal/modules/esm/module_job:78:36)
```

Have you managed to make Nuxt  (generate) and Vue-query work together ? 
(The app work fine when it's in SSR or SPA mode)

**Comment by DamianOsipiuk** [comment]
Hi,
I think this might be an issue with react-query and how it handles  subpackage reexports. This will be fixed in v4 as it's considered a breaking change and in result vue-query v2.
Unless it's another issue, but i would need to play around with it to confirm this.

**Comment by DamianOsipiuk** [comment]
Hi. Could you check if [v2.0.0-alpha.1](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.1) improves the situation?

**Comment by Hebilicious** [comment]
> Hi. Could you check if [v2.0.0-alpha.1](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.1) improves the situation? Be wary of breaking changes though 😅

Hell there, sorry this got lost in notifications.
I will report back !

**Comment by SyntheticGoop** [comment]
This seems to work for me. Cheers!

**Comment by SyntheticGoop** [comment]
It seems to work with the latest alpha and vue-demi 0.13.x. The 0.10.x in the current package.json will not work correctly. (I patched it using yarn resolutions.)

**Comment by DamianOsipiuk** [comment]
[v2.0.0-alpha.5](https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-alpha.5) have update vue-demi version. It should now work without additional changes.

**Comment by chris-visser** [comment]
Confirmed. Upgrading to alpha.5 fixed this issue for me
