### ISSUE TITLE
useMutation is returning plain values, NOT reactive reference ?

### ISSUE THREAD

**Issue by jacobgoh101** [DamianOsipiuk/vue-query#19]
Hi. Thank you for porting `react-query` into Vue. I really like this pattern.

This is the return value of `useMutation `.

```
export interface UseMutationResult<TData = unknown, TError = unknown, TVariables = unknown, TContext = unknown> {
    context: TContext | undefined;
    data: TData | undefined;
    error: TError | null;
    failureCount: number;
    isError: boolean;
    isIdle: boolean;
    isLoading: boolean;
    isPaused: boolean;
    isSuccess: boolean;
    mutate: UseMutateFunction<TData, TError, TVariables, TContext>;
    mutateAsync: UseMutateAsyncFunction<TData, TError, TVariables, TContext>;
    reset: () => void;
    status: MutationStatus;
    variables: TVariables | undefined;
}
```

The returned values are all plain values. **Shouldn't the values be `ref` instead, just like in `useQuery`?**

I am trying to `watch` the value of `isSuccess` but I am not able to, due to it NOT being a reactive value.

How may I solve this?

**Comment by DamianOsipiuk** [comment]
Hi
Yeah it probably should, just to get in line with other hooks.
As of now since it's a reactive object you can try to use it without destructuring. Ex
```
const mutation = useMutation(...)
```
And then access it like `mutation.isSuccess`

Ref: https://v3.vuejs.org/guide/reactivity-fundamentals.html#destructuring-reactive-state
