### ISSUE TITLE
queryKey Typescript Issue - Property 'params' does not exist on type 'string | { params: URLSearchParams; page: number; }'.

### ISSUE THREAD

**Issue by michealroberts** [DamianOsipiuk/vue-query#197]
Firstly, this is an awesome library! Great work.

I'm using as far as I know, the `queryKey` as given in the documentation as follows:

```ts
useQuery(
      ['searchBodies', { params, page }],
      async ({ queryKey }) => {
        const params = queryKey[1].params

        const { data } = await fetchBodies({
          baseURL: new URL(import.meta.env.VITE_PERSEUS_API_BASE_URL),
          version: import.meta.env.VITE_PERSEUS_API_VERSION as '1',
          page: page.value,
          params: params.value
        })

        return data
      },
      {
        retry: 2,
        staleTime: 5000
      }
    )
```

However, I am seeing the following typing issue:

```ts
Property 'params' does not exist on type 'string | { params: URLSearchParams; page: number; }'.
```

<img width="812" alt="Screenshot 2022-06-24 at 17 05 44" src="https://user-images.githubusercontent.com/84131395/175574407-7960f19a-dd3f-4405-8a32-78cc2b545b3b.png">

What would be the usage of the `{ queryKey }` value in typescript? Do you have any examples at all?

**Comment by DamianOsipiuk** [comment]
Hi,
This is how inference works in Typescript for arrays.
What you want to achieve is a tuple type, which indicates which type is in which place in the array.
You could achieve that in two ways.
1.  Create intermediate variable and add a proper typing for it.
    ```ts
    const queryKey: [string, {bar: string}] = ['foo', {bar: 'baz'}]
    useQuery(queryKey, ...)
    ```
3. Add `as const` assertion for the `queryKey`
    ```ts
    useQuery(['foo', {bar: 'baz'}] as const, ...)
    ```
