### ISSUE TITLE
Duplicated data in infinite query

### ISSUE THREAD

**Issue by nicksellen** [DamianOsipiuk/vue-query#206]
Firstly, thanks for the library! I'm just exploring using it for https://karrot.world and so far it's addressing most of the server-state complications we are facing very nicely.

I've ran into a case where my infinite query can show duplicate data, I'll describe it, and if it doesn't make sense, I'll try and create a codepen/similar to reproduce it. The code is [over here](https://github.com/karrot-dev/karrot-frontend/blob/d906504cb24e69d0b7efdfe967b60121074ff23c/src/offers/queries.js#L80-L113).

I'm using the latest beta version (`vue-query@2.0.0-beta.1`)

- backend pagination is cursor-based and limited to 2 results (so I can see the infinite query stuff doing it's thing)
- database has 3 results, and infinite query works nicely
- I delete one entry, and invalidate the query
- it refetches the first page, which gives a `null` value for `getNextPageParam()` as there is only one page of data now
- instead of removing the second page, it keeps it with a `null` value for `pageParam`, which causes it to load a duplicate of the first page

In terms of pages, and pageParams it goes like this (rough code):
```js
// before
{
  pages: [
    [itemA, itemB],
    [itemC],
  ],
  pageParams: [
    null,
    'somecursorvalue',
  ]
}
// after refetch
{
  pages: [
    [itemA, itemB],
    [itemA, itemB],
  ],
  pageParams: [
    null,
    null,
  ]
}
// but I expect it to be
{
  pages: [
    [itemA, itemB],
  ],
  pageParams: [
    null,
  ]
}
```

Thanks!

**Comment by DamianOsipiuk** [comment]
@nicksellen Could you check your `getNextPageParam` function and verify if you are returning `undefined` when there is no next page to be fetched?
Something like: `getNextPageParam: (lastPage) => lastPage.nextPage ?? undefined`

**Comment by DamianOsipiuk** [comment]
That is probably a question to be posted in https://github.com/TanStack/query as i'm not really super familiar with all the quirks of the lib yet
