### ISSUE TITLE
react-query/core is not found when use nuxt2 and vue version is 2.7

### ISSUE THREAD

**Issue by SGAMERyu** [DamianOsipiuk/vue-query#216]
![image](https://user-images.githubusercontent.com/17926105/179653184-d6c6d515-7be1-45c2-a549-ee80161070f3.png)

**Comment by AndreyYolkin** [comment]
https://tanstack.com/query/v4/docs/guides/migrating-to-react-query-4#react-query-is-now-tanstackreact-query

Looks like we need to replace react-query/core to @tanstack/query-core

Also, 4.0.0 released today
