### ISSUE TITLE
Uncaught Error: Cannot find module '@vue/devtools-api'

### ISSUE THREAD

**Issue by BrianMitchL** [DamianOsipiuk/vue-query#218]
v2.0.0-beta.4 (#217 / ce4fcff528ddb3ea969f99bfab19f1be4cfef93b) removed `@vue/devtools-api` as a direct dependency, but it's still being imported, causing an error. Should this be a peerDependency, or added back as a dependency?

**Comment by DamianOsipiuk** [comment]
@BrianMitchL Yeah i think i moved this by accident. It should be reverted as dependency.

**Comment by BrianMitchL** [comment]
Thanks! fixed in #219
