### ISSUE TITLE
Can't access to the cached data

### ISSUE THREAD

**Issue by RomainoSoko** [DamianOsipiuk/vue-query#223]
Hi ! 

Maybe I missed something in the doc, but I can't seem to get the cached queries with the "find" method from queryCache

eg: 
```
const queryCache = new QueryCache({
  onError: (error) => console.log('cache error', error),
  onSuccess: (data) => console.log('cache success', data),
});

const query = queryCache.find(['key']);
```

In query const, the value is always undefined.

Do you have an idea? Thanks !

**Comment by DamianOsipiuk** [comment]
First question would be, if you want to access your data from a Vue component or somewhere else?

If component is the answer, just use `useQuery`.
You can use it in multiple components and all requests with the same `queryKey` will be automatically deduplicated and cached data reused.

If `somewhere else` is the answer, you should create `QueryClient` on your own, before providing it to the `VueQueryPlugin`
```ts
const myClient = new QueryClient(queryClientConfig);
const vueQueryPluginOptions: VueQueryPluginOptions = {
  queryClient: myClient,
};
app.use(VueQueryPlugin, vueQueryPluginOptions);
```
and then access your queries via `myClient.getQueryData` (https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientgetquerydata)
or access QueryCache if you really need to via `myClient.getQueryCache` (https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientgetquerycache)

**Comment by RomainoSoko** [comment]
In fact, I was using it outside a component to access a cached data. What i was doing was to create a queryCache myself instead of using the cache from the default client (like below) --'.

![image](https://user-images.githubusercontent.com/33908717/182408507-247af3ca-d79e-43b7-a473-8b579a6168fe.png)

Thank you very much !

**Comment by keithrz** [comment]
THIS is the code I have been searching for!!!
```
const myClient = new QueryClient(queryClientConfig);
const vueQueryPluginOptions: VueQueryPluginOptions = {
  queryClient: myClient,
};
app.use(VueQueryPlugin, vueQueryPluginOptions);
```

I don't see any documentation on what kind of options you can have for VueQueryPlugin, either in this repo's README or in the docs at the TanStack site.  **_Would it be possible to get some documentation on VueQueryPlugin options added to TanStack docs?_**

Now that I know that the plugin actually has options, I've found more info in the TypeScript types for VueQueryPlugin.  I can simplify that example a bit:
```
app.use(VueQueryPlugin, { queryClientConfig });
```

**Comment by DamianOsipiuk** [comment]
@keithrz  I think you are looking for these pages:
https://tanstack.com/query/latest/docs/vue/guides/custom-client
https://tanstack.com/query/latest/docs/vue/reference/QueryClient

**Comment by keithrz** [comment]
That first link is exactly what I was looking for. Thank you very much,
@DamianOsipiuk !
