### ISSUE TITLE
useQueries doesn't seem to unpack deep ref options

### ISSUE THREAD

**Issue by Evertt** [DamianOsipiuk/vue-query#227]
I mean, I can do it myself, but I thought vue-query was made to do it for me. It works with the normal `useQuery()`.

So I'm talking about the `enabled` option for example. Which can be a ref or a computed and then when you use it in `useQuery()` then it automatically unwraps the ref/computed. But when I use it in `useQueries()` I get an error from react-query that `enabled` is not a boolean and indeed, when I check, it is indeed still a computed.

Oh yeah I'm using version 1.25.2 btw.

**Comment by DamianOsipiuk** [comment]
Well,
In v1 only `useQuery`/`useInfiniteQuery` unwrap refs automatically.
In v2 all composables besides `useQueries`.

So it is something that needs to be added and possibly back ported to v1

**Comment by Evertt** [comment]
I think so, personally. Like it's just strange that `useQuery()` would `cloneDeepUnref` the options, but `useQueries()` wouldn't. And unfortunately you don't export `cloneDeepUnref`, so now I have to copy that function to my own `src` folder.

**Comment by DamianOsipiuk** [comment]
The idea is not to implement it on your side, but contribute to the repository and add a support for it for everyone to use 😉

**Comment by DamianOsipiuk** [comment]
@Evertt Try https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.26.0

**Comment by Evertt** [comment]
I tried, and at first it seemed to work, but later it seemed like the attributes that I get back every query, like `data`, stopped being reactive. So I went back to 1.25 and my previous workaround. 😬

**Comment by DamianOsipiuk** [comment]
Few question:
- could you check if with the latest version you are passing `queries` array as `reactive`?
- is is possible that your workaround stabilized the queries order in the array?
- what Vue version are you using?

**Comment by DamianOsipiuk** [comment]
This should be fixed in @tanstack/vue-query
