### ISSUE TITLE
Calling suspense on a query ignores the `enabled` config option

### ISSUE THREAD

**Issue by SyntheticGoop** [DamianOsipiuk/vue-query#229]
Version: `2.0.0-beta.5`

Possibly related to #200.

When calling `useQuery({ enabled: false })).suspense()` the query will run regardless of the `enabled` value being `false`.

Context:

I'm chaining query calls like this:
```ts
const enabled: Ref<boolean> = ... // Some reactive value from somewhere, ie Provide/Inject
const data = await useQuery({ enabled }).suspense()
```

My intent is to suspend the component from loading until enabled is set to true. In my case, I'm waiting on a global auth state to become true.

I'll be happy to help contribute in a PR.

Side issue: Does the dev tools update the state of the options if the options are reactive and change? It doesn't seem to update in my case.

**Comment by kevin-courbet** [comment]
I had a related quirk (#234) with suspense. It seems it always triggers the refetch when you call it, regardless of staleness / cache / anything whatsoever. 

For now, I ended up working my way around it with 
```ts
watch(isFetching, (isFetching) => { 
    // do whatever needs to happen after the query runs
 })
```
Sounds like in your case you might as well just watch enabled. 

Wonder what @DamianOsipiuk thoughts are on the expected behaviour of suspense

**Comment by DamianOsipiuk** [comment]
As i tested it before, giving query enough stale time should actually resolve immediately.
Maybe i need to retest that, but i'm quite positive it worked before.
As for enabled, not sure. Looking at the tests in `react-query` it should work, but need to test it out as well.

**Comment by rompetomp** [comment]
FWIW, I have the same issue (on version `^1.26.0`). I'm using nuxt, and one of my queries is dependent on the other, so I use the `enabled` option like this:

```typescript
export function useSearchResultListQuery(params) {
  const { data: locationsRecords, isFetched: locationsFetched } = useLocationsQuery()
  return useQuery(['searchResultList', params.value], () => {
    // ...
    // I use `locationsRecords` in this block.
  },
  {
    enabled: locationsFetched // I tried this with locationsFetched.value also
  })
}
```

Then, in my Vue component, I do this:
```typescript
const { isError, isLoading, data, suspense } = useSearchResultListQuery(searchData)
onServerPrefetch(async () => {
  await suspense
})
```

and I get the error that `locationsRecords` is empty, while it should contain values, because it should wait for the `useLocationsQuery` to resolve.

I tried to make this as compact as possible, but if you have any questions, do let me know

**Comment by DamianOsipiuk** [comment]
@SyntheticGoop @kevin-courbet @rompetomp 
Please try https://github.com/DamianOsipiuk/vue-query/releases/tag/v2.0.0-beta.7 and let me know if it fixes your issue.

**Comment by kevin-courbet** [comment]
I have a very good setup to test this, and unfortunately this didn't change the behaviour I was experiencing.

```
// mounting and unmounting repeatedly this component will observe staleness options - no network call is made 
const { isLoading, data: profiles, isFetching } = getUsers();

// mounting and unmounting repeatedly executes the network query each time
const { isLoading, data: profiles, isFetching, suspense } = getUsers();
await suspense()

```

**Comment by DamianOsipiuk** [comment]
@kevin-courbet I could not reproduce the issue you are describing - https://codesandbox.io/s/restless-leftpad-vvegbk?file=/src/Page.vue

with both for loop and component remounting (change page button)

**Comment by jackmellis** [comment]
Just discovered I was having this same issue. I have a query that is dependent on another query. My component is attempting to suspense on the first query, and this is forcing it to run even though enabled is false....

**Comment by kevin-courbet** [comment]
@DamianOsipiuk strange, the setup looks identical... I played around with the sandbox but couldn't reproduce the issue either. Not sure what could explain the difference in behaviour yet. I'm using bare Vue3 with Vite, and setup script tags. The only thing that is different at this point is the setup script tag. I wonder if that messes up with it somehow. Will try to investigate it when I have the time

**Comment by ayhanfuat** [comment]
I was having the same issue and came here to check. I can confirm that it works as expected using the latest release (^2.0.0-beta.10).

**Comment by DamianOsipiuk** [comment]
🎉
