### ISSUE TITLE
Failing to enable caching with `useQueries`

### ISSUE THREAD

**Issue by mfigurski80** [DamianOsipiuk/vue-query#233]
As the title indicates, I'm having trouble seeing any effects of the cache with the `useQueries` function. Will include the code I'm testing below. While the query itself works, properly running `fetchBond` and returning correct results, both localstorage and cache in my browser remain empty, and a refresh of the page prompts the loading of new data (no stale data appears, I get a full loading state)

I'm hoping to write a web3 query with a composable like this: 

``` typescript
export const useBondListQuery = (
  bondIds: number[] | Ref<number[]>,
  options?: Omit<
    UseQueryOptions<unknown, unknown, unknown, (string | number)[]>,
    "queryFn" | "queryKey"
  >
) => {
  const { status } = useWeb3();
  const { contracts } = useContracts();

  const queryKeys = computed(() =>
    ((bondIds as Ref<number[]>).value || bondIds).map((bondId) => ({
      queryKey: ["bond", bondId],
      queryFn: (ctx: QueryFunctionContext) =>
        fetchBond(contracts.value.Core, ctx),
      ...queryOptions,
      ...options,
      enabled:
        bondId !== undefined &&
        status.value === ConnectionStatus.CONNECTED &&
        contracts.value.Core !== undefined &&
        (options?.enabled ?? true),
    }))
  );

  return useQueries(queryKeys) as readonly QueryObserverResult<
    FetchBondResult,
    unknown
  >[];
};
```

I've changed some cache settings in an attempt to fix this. The `queryOptions` you see referenced is containing these. As you can see, I'm hoping to minimize queries and store a lot of this data on browser cache if possible (it's mostly static data tbh).

``` typescript
const queryOptions = {
  refetchOnWindowFocus: false,
  cacheTime: 1000 * 60 * 5,
  staleTime: 1000 * 60 * 5,
  retry: false,
};
```

Let me know if this is possible or if I'm missing something from the documentation entirely

**Comment by DamianOsipiuk** [comment]
Hi,
Just to confirm, you cannot see those queries in the devtools?

Could you also tell me:
- are you using v1 or v2?
- are you using `useQueryProvider` or `VueQueryPlugin`? (also double check if you do not use mix of it or multiple providers)

**Comment by mfigurski80** [comment]
Hey! Thanks for trying to help

To confirm -- I can see these queries re-appear in devtools when I use this composable -- they are not present beforehand, like I would expect them to if they're being cached between sessions

- I'm not sure -- I'm using vue-query v1.25.2, but that appears to be close to latest. How do I check this? I'm on vue 3.2.13 btw

- I'm using VueQueryPlugin in the main.ts of my app, as shown below. `useQueryProvider` is not present in the repository.

``` typescript
createApp(App)
  .use(router)
  .use(VueQueryPlugin)
  .use(VueCookies)
  .use(PrimeVue)
  .mount("#app");
```

**Comment by DamianOsipiuk** [comment]
I think the keyword that you use here is `sessions`.

Vue-Query does not store the data between sessions by default.

Vue-Query caches the data between multiple calls to the same endpoint in one session. Ex multiple components request same data, or you navitage to a different page in the app and back.

To make data persist between multiple sessions you would have to use persist plugin. Unfortunately it's not yet ported to Vue-Query. I intend to add that capability after migration to @tanstack monorepo.

**Comment by mfigurski80** [comment]
Ahh okay everything now makes sense. I suppose I can temporarily add this functionality by writing to localstorage after some queries and loading them in every session. Or even inside my fetch function.

I can now see that this was crossed off on the roadmap -- apologies about not reading through the repo fully, and thanks for all the work you're doing on this!

**Comment by mfigurski80** [comment]
For reference, for anybody trying to cache data between sessions, this is eventually what I settled on. This can be adapted for a singular `useQuery` call as well, probably.

``` Typescript
export const useBondListQuery = (bondIds: Ref<(number | undefined)[]>) => {
  const { status } = useWeb3();
  const { contracts } = useContracts();

  const queryKeys = computed(() =>
    bondIds.value.map((bondId) => {
      const cacheKey = computeCacheKey(["bond", bondId]);
      return {
        queryKey: ["bond", bondId],
        queryFn: (ctx: QueryFunctionContext) =>
          persistQueryResult(
            fetchBond(contracts.value.Core, bondId as number),
            computeCacheKey(ctx.queryKey)
          ),
        ...queryOptions,
        enabled:
          bondId !== undefined &&
          status.value === ConnectionStatus.CONNECTED &&
          contracts.value.Core !== undefined,
        initialData: pullQueryCache<FetchBondResult>(cacheKey)?.data,
        initialDataUpdatedAt:
          pullQueryCache<FetchBondResult>(cacheKey)?.updated,
      };
    })
  );

  return useQueries(queryKeys);
};
```

To support this structure, I added a file like this to my 'utils':
``` Typescript
export type CacheStructure<T> = { data: T; updated: number };

export function computeCacheKey(ctx: string | readonly unknown[]): string {
  return `CACHED_QUERY_${Array(ctx).join("_")}`;
}

export function pullQueryCache<T>(key: string): CacheStructure<T> | undefined {
  const cache = window.localStorage.getItem(key);
  return cache ? JSON.parse(cache) : undefined;
}

export function persistQueryResult<T>(p: Promise<T>, key: string) {
  return p.then((result) => {
    window.localStorage.setItem(
      key,
      JSON.stringify({ data: result, updated: Date.now() } as CacheStructure<T>)
    );
    return result;
  });
}
```

**Comment by chetzof** [comment]
> I think the keyword that you use here is `sessions`.
> 
> Vue-Query does not store the data between sessions by default.
> 
> Vue-Query caches the data between multiple calls to the same endpoint in one session. Ex multiple components request same data, or you navitage to a different page in the app and back.
> 
> To make data persist between multiple sessions you would have to use persist plugin. Unfortunately it's not yet ported to Vue-Query. I intend to add that capability after migration to @TanStack monorepo.

Is see that the package was migrated to @Tanstack monorepo. Is is possible to use the persist plugin already?

**Comment by DamianOsipiuk** [comment]
@chetzof Hi, yes it's possible. Please refer to the example - https://github.com/TanStack/query/blob/main/examples/vue/persister/src/main.ts
