### ISSUE TITLE
Vue-Query Dev Tools Not Showing In Vue-Devtools

### ISSUE THREAD

**Issue by aaronksaunders** [DamianOsipiuk/vue-query#236]
Running the latest version of vue-dev tools
Version 6.2.1
Updated July 13, 2022

Running Latest Version of Vue Query

Is there some additional configuration I need to do?

Thanks

<img width="910" alt="Screen Shot 2022-09-02 at 3 11 26 PM" src="https://user-images.githubusercontent.com/524953/188222040-e6f8421c-e237-4e60-bbb0-73d68b4ec345.png">

**Comment by DamianOsipiuk** [comment]
So it seems that `vue-query` is properly registered.
Now you need to switch to the `inspector` and choose `vue-query` inspector.

![image](https://user-images.githubusercontent.com/28151934/188514697-caaf2695-6a4b-41ab-bfaf-d4dff009be36.png)

**Comment by aaronksaunders** [comment]
that is what I am doing
- https://www.loom.com/share/f9fe60c27e0a44e5b8acfab75e4a18d1

**Comment by DamianOsipiuk** [comment]
It seems that you do not have any queries in the cache.
Make sure to remove usage of any `useQueryProvider` in your app as it might overwrite the client that is being set-up by the plugin.

**Comment by aaronksaunders** [comment]
@DamianOsipiuk - that solved it, I thought I saw in the example the use of `useQueryProvider`, I will have to take a better look at the documentation. Thanks

**Comment by DamianOsipiuk** [comment]
I actually replaced `useQueryProvider` with `VueQueryPlugin` at some point.
If you notice that `useQueryProvider` is used somewhere, let me know and i will remove it. 😉

**Comment by kathirr007** [comment]
@aaronksaunders I'm also facing the same issue. Could you please help me with this?

App setup in chrome:
![image](https://user-images.githubusercontent.com/13422232/188702671-a7c7bf71-aa12-4d1e-9bcf-06ba4e2d916e.png)

My maint.ts file looks like this:
![image](https://user-images.githubusercontent.com/13422232/188702962-8e2e2fcd-f17b-4385-a648-ad5e33128b0f.png)

**Comment by Ask1n** [comment]
> I actually replaced `useQueryProvider` with `VueQueryPlugin` at some point. If you notice that `useQueryProvider` is used somewhere, let me know and i will remove it. 😉

vite-ssr example does not include `VueQueryPlugin` and vue-query not showing in dev tools, but if iclude `app.use(VueQueryPlugin)` its work
How to correctly connect vue-query with vite-ssr?

**Comment by DamianOsipiuk** [comment]
> I'm also facing the same issue. Could you please help me with this?

@kathirr007 
1. Search your codebase for `useQueryProvider` usage and remove it if found.
2. Make sure that you do not create QueryClient anywhere else in your app.

**Comment by DamianOsipiuk** [comment]
> vite-ssr example does not include `VueQueryPlugin` and vue-query not showing in dev tools, but if include `app.use(VueQueryPlugin)` its work
> How to correctly connect vue-query with vite-ssr?

Replace
```ts
// Mount and provide the client to the app components
client.mount();
app.provide(VUE_QUERY_CLIENT, client);
```

with

```
app.use(VueQueryPlugin, { queryClient: client });
```
