### ISSUE TITLE
vue-query hooks not work on nuxt v 2.15.8

### ISSUE THREAD

**Issue by niyayeshpansion** [DamianOsipiuk/vue-query#237]
vue-query hooks can only be used inside setup() function.

**Comment by DamianOsipiuk** [comment]
Hi,
I would need more information on what if your setup, how did you set it up, vue-query version etc.

It definitely works as this version is about a year old and there is a working example with vue2: 
https://github.com/DamianOsipiuk/vue-query/tree/beta/examples/nuxt-simple
