### ISSUE TITLE
error with Nuxt 3 rc

### ISSUE THREAD

**Issue by Gants102** [DamianOsipiuk/vue-query#243]
Hello,
I am using Nuxt 3.0.0-rc.8. I am also using the beta version of vue-query v2. I have been following the code from the docs and get the following error:

```
[nuxt] [request error] [unhandled] [500] Cannot read properties of undefined (reading 'vue-query')
  at ./.nuxt/dist/server/server.mjs:5976:36  
  at ./node_modules/hookable/dist/index.mjs:39:70  
  at async ./.nuxt/dev/index.mjs:539:3  
  at async ./.nuxt/dev/index.mjs:107:22  
  at async ./node_modules/h3/dist/index.mjs:592:19  
  at async Server.nodeHandler (./node_modules/h3/dist/index.mjs:538:7)
```

I also had a problem with the original code in the docs as it needed to be wrapped in `defineNuxtPlugin` the modified code I've used for the plugin is below:

```
import {
    VueQueryPlugin,
    VueQueryPluginOptions,
    QueryClient,
    hydrate,
    dehydrate,
  } from "vue-query";
  
  export default defineNuxtPlugin(nuxtApp => {
    // Modify your Vue Query global settings here
    const queryClient = new QueryClient({
      defaultOptions: { queries: { staleTime: 1000 } },
    });
    const options: VueQueryPluginOptions = { queryClient };
  
    nuxtApp.vueApp.use(VueQueryPlugin, options);
  
    if (process.server) {
      nuxtApp.hook("app:rendered", () => {
        nuxtApp.nuxtState["vue-query"] = dehydrate(queryClient);
      });
    }
  
    if (process.client) {
      nuxtApp.hook("app:created", () => {
        hydrate(queryClient, nuxtApp.nuxtState["vue-query"]);
      });
    }
  });
```
 
If I remove the if statements the code works and can get data using `useQuery` and the data gets fetched and is checking at the correct intervals but just not pulling changes.

**Comment by DamianOsipiuk** [comment]
Hi, please refer to the nuxt 3 example https://github.com/DamianOsipiuk/vue-query/blob/main/examples/nuxt3-simple/plugins/vue-query.ts

Do you feel like updating docs to contain the proper plugin code?

**Comment by Gants102** [comment]
Hello,
Thank you have got it working now and sent a request to update the docs :-)
