### ISSUE TITLE
Could you add QueryObserver export?

### ISSUE THREAD

**Issue by onkarj422** [DamianOsipiuk/vue-query#25]
So, I am in a situation where I need to use query result outside a composable function or setup. According to the QueryObserver api, the way to achieve that would be -
```javascript
import { QueryObserver } from 'vue-query';
import { queryClient } from 'myQueryClient';

const classesObserver = new QueryObserver(queryClient, { queryKey: ['classes', dependencies] });
const classesData = classesObserver.getCurrentResult().data;
```

Now, difference between using query observer's getCurrentResult vs using query client's getQueryData/getQueryState would be
query observer will return the actual data which is cached along with its transformation done using select option. Whereas, queryClient's getQueryData/getQueryState will return just the response data.

So, could you possibly add QueryObserver to the vue-query exports?

**Comment by DamianOsipiuk** [comment]
@onkarj422 Hi, I'm ok with exposing additional classes as there might be some corner cases that could require those.

I might not have the full context of your use case, so ignore the rest of the comment if it's not applicable.

As for your example, don't you think that it is a little overkill to use the whole QueryObserver just to run a `select` function?
I guess you could use it like:
```
import { queryClient } from 'myQueryClient';

const myData = queryClient.getQueryData(queryKey);
const myTransformedData = mySelectFunction(myData);
```
And maybe create some util function from it.

Also `QueryObserver` will try to fetch your data from the server, while `getQueryData` will operate only on the cache.
Depending on what you need you might want to use `getQueryData` or [queryClient.fetchQuery](https://react-query.tanstack.com/reference/QueryClient#queryclientfetchquery)

**Comment by DamianOsipiuk** [comment]
Solved in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.5.0

**Comment by onkarj422** [comment]
> Solved in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.5.0

Thank you for such quick resolution!

**Comment by onkarj422** [comment]
Hello, I think version 1.5.0 is not released to npmsjs?

npm install says version vue-query@1.5.0 not found

**Comment by DamianOsipiuk** [comment]
Works for me, maybe you have another registry set-up?

**Comment by onkarj422** [comment]
> Works for me, maybe you have another registry set-up?

Yeah i have another registry setup, but how do i update then?
