### ISSUE TITLE
How do you reset/clear the cache of all queries?

### ISSUE THREAD

**Issue by Petri-Oosthuizen** [DamianOsipiuk/vue-query#256]
Usecase: signing a user out should clear the cache for that user so that no data can be leaked to another user.

**Comment by DamianOsipiuk** [comment]
Hi, i think you are looking for this: https://tanstack.com/query/v4/docs/reference/QueryClient#queryclientclear

**Comment by Petri-Oosthuizen** [comment]
Ah, it's in the new docs, was looking for something similar in the [old docs](https://vue-query-next.vercel.app).
