### ISSUE TITLE
webpack loaders with nuxt-bridge

### ISSUE THREAD

**Issue by esamani77** [DamianOsipiuk/vue-query#259]
Hey there, I tried to use `vue-query` with `nuxt` framework with `nuxt-bridge` version.
But I faced with this problem, What should I do? 
![image](https://user-images.githubusercontent.com/40516046/195976499-df780ec8-84e2-4fa1-a789-0a38c8cf8940.png)

**Comment by DamianOsipiuk** [comment]
Try adding this to your nuxt config:
```ts
import { defineNuxtConfig } from "@nuxt/bridge";

export default defineNuxtConfig({
  build: {
    transpile: ["vue-query", "vue-demi"],
  }
})
```

**Comment by esamani77** [comment]
thanks. it works.
