### ISSUE TITLE
My query is running even though it is disabled, how is that possible?

### ISSUE THREAD

**Issue by Evertt** [DamianOsipiuk/vue-query#261]
I'm sorry that I can't give you a small repro. I also don't understand what makes this happen, because normally the `enabled` option is honored.

But in any case, here's the proof:

<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1267282/198021999-8760e0d2-b262-4682-bdb7-66a276bbe15c.png">

I don't know if it's clear, but my breakpoint *inside* `queryFn` has triggered, even though you can see on the right that `enabled` is still `false`. Which it should be, since my `queryKey` still contains a `null` value, because it's still waiting to find out which `id` it's supposed to fetch.

Any idea how this is possible? I'm using v1.25 btw.

**Comment by DamianOsipiuk** [comment]
Do you by any chance use `suspense` with this query?
Also triggering some methods on the `query` or `queryClient` like `refetch` will bypass `enabled` state.

**Comment by Evertt** [comment]
Shit, yeah I was refetching somewhere which I hadn't noticed. 🤦‍♂️

Thanks 😅
