### ISSUE TITLE
Using VueQueryPlugin doesn't work for me - bring back `useQueryProvider`?

### ISSUE THREAD

**Issue by stellR42** [DamianOsipiuk/vue-query#267]
I use `vue-query` in several packaged components that I have. Because they're only components, there is no app instance that I can use the `VueQueryPlugin` with.  Instead, I've been using `useQueryProvider` in the top-level component of each package. The result is that there are multiple query providers in the consuming app, but it's been working great.

Now I'm trying to migrate to v2 but I see that `useQueryProvider` has been removed in favor of only supporting the `VueQueryPlugin`. This essentially disables my ability to use `vue-query` at all. Are there any workarounds that you can suggest, or maybe you can bring `useQueryProvider` back?

**Comment by DamianOsipiuk** [comment]
Ideally you should not create multiple `QueryClient`'s. Idea is to have one `QueryClient` in the app to leverage shared cache.

Your components could use `useQuery`, but do not use `provider` nor `plugin`.
The application in which you will be using those components, could have `VueQueryPlugin` instantiated, which will `provide` the `QueryClient` instance trough the component tree.

Other method would be to create `QueryClient` yourselfin once place and then provide this instance to `useQuery` composables as an option.
