### ISSUE TITLE
TRPC integration?

### ISSUE THREAD

**Issue by kylegl** [DamianOsipiuk/vue-query#273]
Hey man, thanks for all your hard work on vue-query. Awesome to have this tool in Vue now. 

Quick question for you: have you ever thought about integrating this with TRPC? TRPC has an integration for react [@trpc/react-query](https://trpc.io/docs/react-query) would be amazing to have something similar to this for Vue.

Just wondering if you have seen/thought about this and if you have any pointers on how to get this started?

Thanks for your time!

**Comment by DamianOsipiuk** [comment]
Hi, unfortunately i do not have enough time currently to create and maintain such package.
Maybe when trpc 11 comes up with cleaned up codebase after compatibility layer removal.

If demand for it would be high, maybe someone from the community would step up and create it.

**Comment by michealroberts** [comment]
I'm very much interested in tRPC, and believe the benefits it brings to typesafety (alongside an ORM like prisma) are huge.

I'd be interested to work on an adapter for vue-query.
