### ISSUE TITLE
useQueries not working when array of query options is computed (dynamic number of queries)

### ISSUE THREAD

**Issue by onkarj422** [DamianOsipiuk/vue-query#34]
Hello, its me again

So, here's something I was trying with useQueries. I am trying make useQueries work with dynamically created query options. This will let me call todos for multiple ids which are dynamically passed to the hook.

```javascript
function useMultipleTodos() {
  const ids = ref([]);
  const queries = computed(() => ids.value.map((id) => ({
    queryKey: ['post', reactive({ id })],
    queryFn: todoFetcher(id),
    enabled: !!id,
  })));
  const queryResults = useQueries(queries.value);
  return reactive({
    queryResults,
    ids,
    queries,
    fetch: (_ids) => { ids.value = _ids; }
  });
}
```
and in the component I would use it something like this

```javascript
export default defineComponent({
  name: "App",
  components: { VueQueryDevTools },
  setup() {
    useQueryProvider();
    return {
      multipleTodos: useMultipleTodos(),
    };
  },
  methods: {
    onFetchMultipleTodos() {
      this.multipleTodos.fetch([1,2,3]);
    }
  }
});
```

Now, when my onFetchMultipleTodos method is called, it calls fetch method and fetch method sets ids ref to [1,2,3]. This in turn makes a change in queries computed. But, still queries are not called, nothing in the vuequery dev console.

Here's the link to the repo which reproduces this in our basic-vue-2 example.
[https://github.com/onkarj422/reproduce_use_queries](https://github.com/onkarj422/reproduce_use_queries)

**Comment by DamianOsipiuk** [comment]
Hi, I think that you are losing the reactivity when passing `useQueries(queries.value);`
I think this should look like `useQueries(queries);` where queries would be a `reactive([])`.
There are some quirks to that, which you can check here: https://vuejs.org/v2/guide/reactivity.html#For-Arrays

Also, I think I have discovered a bug with the Vue2 + Devtools that causes an infinite loop in the application. This does not happen in Vue3.
So for now make sure to keep dev tools closed when experimenting and noticing page freeze.

**Comment by onkarj422** [comment]
> Hi, I think that you are losing the reactivity when passing `useQueries(queries.value);`
> I think this should look like `useQueries(queries);` where queries would be a `reactive([])`.
> There are some quirks to that, which you can check here: https://vuejs.org/v2/guide/reactivity.html#For-Arrays
> 
> Also, I think I have discovered a bug with the Vue2 + Devtools that causes an infinite loop in the application. This does not happen in Vue3.
> So for now make sure to keep dev tools closed when experimenting and noticing page freeze.

Yes, that is correct. I lose the reactivity when I use queries.value. But, when I pass queries as it is, it throws following error.

![image](https://user-images.githubusercontent.com/20082972/122228953-f93fdc80-ced5-11eb-9473-43013d62b727.png)

I think it does not accept a ref, it needs a reactive object. But, can arrays be used with reactive([])?

**Comment by onkarj422** [comment]
Here's something I just tried, doesn't work either.

```javascript
function useMultipleTodos() {
  const queriesArr = reactive({
    queries: [],
  });
  const queryResults = useQueries(queriesArr.queries);
  return reactive({
    queryResults,
    queries: queriesArr,
    fetch: (_ids) => {
      queriesArr.queries = _ids.map((id) => reactive({
        queryKey: ref(['post', reactive({ id })]),
        queryFn: todoFetcher(id),
      }));
    },
  });
}
```

**Comment by DamianOsipiuk** [comment]
@onkarj422 You could try something like this: https://codesandbox.io/s/magical-pasteur-hd6jj?file=/src/App.vue
It does not register the queries in devtools for some reason (need to investigate why), but when you inspect the network tab, they are fetched.

**Comment by onkarj422** [comment]
> @onkarj422 You could try something like this: https://codesandbox.io/s/magical-pasteur-hd6jj?file=/src/App.vue
> It does not register the queries in devtools for some reason (need to investigate why), but when you inspect the network tab, they are fetched.

Tried it, although the call is made, queryResults is still an empty array. Can't access data.

**Comment by DamianOsipiuk** [comment]
Hmm. I will take a look at this after next week. Since I don't have access to PC right now.

In the mean time you could try to reproduce the same thing with react and react-query and check whether it's a limitation there as well or it's a bug on vue-query side.

**Comment by onkarj422** [comment]
> Hmm. I will take a look at this after next week. Since I don't have access to PC right now.
> 
> In the mean time you could try to reproduce the same thing with react and react-query and check whether it's a limitation there as well or it's a bug on vue-query side.

I actually checked with the react-query, it works there. Seems like a bug one vue-query side. I will again check the same thing with a vue 3 example and update here.

**Comment by DamianOsipiuk** [comment]
@onkarj422 Issue should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.7.1
You can check it out at https://codesandbox.io/s/magical-pasteur-hd6jj?file=/src/App.vue

In case it does not work for you, feel free to reopen the ticket.

**Comment by onkarj422** [comment]
> @onkarj422 Issue should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.7.1
> You can check it out at https://codesandbox.io/s/magical-pasteur-hd6jj?file=/src/App.vue
> 
> In case it does not work for you, feel free to reopen the ticket.

Yep, it's working in the codesandbox now. I still need to check it in my project once. Anyway, thanks a lot!
