### ISSUE TITLE
QueryCache is private

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [DamianOsipiuk/vue-query#38]
Hi,

I'm coming to vue-query after using react-query and the [QueryCache](https://react-query.tanstack.com/reference/QueryCache) is very powerful feature. Looking at the exports of this library QueryCache is missing.

https://github.com/DamianOsipiuk/vue-query/blob/main/src/index.ts

Is there a reason that this feature is being omitted in `vue-query` or can we expose it? Note, I'd be happy to create the PR.

**Comment by DamianOsipiuk** [comment]
Hi,
It's a missed re-export along with MutationCache.
I would say that both should be re-exported. 📦 

PR is welcome. 👍

**Comment by RyanAtViceSoftware** [comment]
@DamianOsipiuk I made the change but when I try and push my branch it's giving me auth errors. Do you need to add me or do I need to fork or something?

```
vue-query-official on  38-QueryCache-is-private is 📦 v1.0.0-semantic via  v14.16.1 took 9s 
❯ git push --set-upstream origin 38-QueryCache-is-private
Username for 'https://github.com': ryan@vicesoftware.com
Password for 'https://ryan@vicesoftware.com@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/DamianOsipiuk/vue-query.git/'
```

**Comment by jueinin** [comment]
may be you need fork this repo. And push to your own repo.finally submit a PR

**Comment by RyanAtViceSoftware** [comment]
@jueinin thanks for clarifications. sorry first time PR'n an OSS. Please find PR ready for review here: https://github.com/DamianOsipiuk/vue-query/pull/39

@DamianOsipiuk @jueinin how long does it usually take for these changes to make it into the the latest nuget? I'm working on setting up a demo project with vue-query for a client to consider bringing it into their code base.

**Comment by DamianOsipiuk** [comment]
@RyanAtViceSoftware Released in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.6.2
