### ISSUE TITLE
Re-export extra types from react-query

### ISSUE THREAD

**Issue by rubenmoya** [DamianOsipiuk/vue-query#46]
Hello!

I'm wrapping the `useQuery` in custom hooks to reuse them accross the application, for example:

```ts
export const useFetchTodos = (options) => {
  return useQuery('todos', todosFetcher, options)
}
```

The problem I'm facing is that I'd need `UseQueryOptions`  to be able to type it, since otherise it's `any`. I was thinking about opening a PR adding that type to the `index.ts` :

```ts
export type {
  UseQueryOptions
} from "react-query/types";
```

What do you think?

**Comment by DamianOsipiuk** [comment]
Hi,
I would say that it would be beneficial to reexport all types instead of exporting them one by one.
Maybe in a similar fashion like in main package like `vue-query/core-types` or something similar to not pollute the main entry point and avoid name clashing.

What do you think? 🤔

**Comment by jueinin** [comment]
Why not import type directly from react-query?

**Comment by NikitaIT** [comment]
It seems reasonable to make the exports as similar as possible to react-query. This will provide great DX. So far, I really like the fact that I can use the documentation for react-query with vue-query and the examples work there.

**Comment by DamianOsipiuk** [comment]
Types should be available under `vue-query/types` in version https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.8.0
