### ISSUE TITLE
How can we use a computed property in the query key (e.g. page number)?

### ISSUE THREAD

**Issue by bikegriffith** [DamianOsipiuk/vue-query#47]
The react-query docs describe how to use a compound query key ([Array Keys](https://react-query.tanstack.com/guides/query-keys#array-keys)). I want to be able to do something similar with vue-query, but I've struggled to make it work.

💡  Proposed Vue 3 Composition API Example:
```ts
export default defineComponent({
  // ...
  setup: (props) => {
    const queryKey = `widgets:${props.query}`;
    const page = ref(0);
    const { data: widgets, isFetching: fetching } = useQuery<Widget[]>(
      reactive([queryKey, computed(() => page.value)],
      () =>
        getWidgets({
          p: page.value,
          q: props.query,
        })
    )
})
```

... but that doesn't work as-is.  Changing the page value does not trigger a re-query. The `computed` does't appear to do anything; and otherwise I need to explicitly trigger an invalidation (e.g. `queryClient.invalidateQueries([queryKey, 0]);`).  

Is there some other method I'm missing for how to use a reactive value in the QueryKey?

**Comment by DamianOsipiuk** [comment]
Hi @bikegriffith,
Reactivity in Vue is... very hard to nail down. It has some quirks that you have to be aware of.

You almost nailed it down.
If you take a look at the third code block from the Readme, you will notice that ref is passed to the object, not directly to the query key array.

So in your case, something like this should work:
```js
export default defineComponent({
  // ...
  setup: (props) => {
    const queryKey = `widgets:${props.query}`;
    const page = ref(0);
    const { data: widgets, isFetching: fetching } = useQuery<Widget[]>(
      reactive([queryKey, {page}]),
      () =>
        getWidgets({
          p: page.value,
          q: props.query,
        })
    )
})
```

Let me know if that works for you.

**Comment by bikegriffith** [comment]
@DamianOsipiuk That worked!  I thought I had tried every permutation around making it reactive, but I missed that one!  Thank you!  I appreciate the help!

**Comment by andresespinosapc** [comment]
Does anyone know why it has to be like this? It makes more sense to me that it should work with a computed. Also, I don't know why it only works as an object instead of directly as an element of the array, and why it is not needed to use `.value`

**Comment by wobsoriano** [comment]
> Does anyone know why it has to be like this? It makes more sense to me that it should work with a computed. Also, I don't know why it only works as an object instead of directly as an element of the array, and why it is not needed to use `.value` @DamianOsipiuk
> 
> Also I don't know how to use a computed value inside the queryKey. For example, I have this:
> 
> ```
> const selectedCategory = ref(null);
> const selectedCategoryId = computed(() => selectedCategory.value?.id);
> ```
> 
> How do I use `selectedCategoryId` inside my queryKey?

https://vue-query.vercel.app/#/guides/query-keys?id=array-keys

**Comment by DamianOsipiuk** [comment]
@andresespinosapc 
Unfortunately Vue reactivity cannot unwrap a ref directly in the array as mentioned in official Vue docs: https://v3.vuejs.org/guide/reactivity-fundamentals.html#access-in-reactive-objects
> Ref unwrapping only happens when nested inside a reactive Object. There is no unwrapping performed when the ref is accessed from an Array or a native collection type like Map

Second relevant piece of information is that Vue cannot track plain object changes, and uses ES6 proxies for that. If you unwrap it by yourself, Vue will loose abili to track changes for it. https://v3.vuejs.org/guide/reactivity.html#how-vue-tracks-these-changes

**Comment by andresespinosapc** [comment]
@DamianOsipiuk thanks! I forgot to wrap it into an object. Thanks for the reference to the documentation, it is all crystal clear to me now 😄
