### ISSUE TITLE
 Functions do not have to be Ref?

### ISSUE THREAD

**Issue by NikitaIT** [DamianOsipiuk/vue-query#48]
```
const { data, refetch } = useQuery("key", () => Promise.resolve(1), {
      refetchOnWindowFocus: false,
      enabled: false,
    });
refetch.value(); // manual exec
```

**Comment by wobsoriano** [comment]
[useBaseQuery](https://github.com/DamianOsipiuk/vue-query/blob/main/src/useBaseQuery.ts) returns a `ref` that's why. Check line 45.

**Comment by DamianOsipiuk** [comment]
Hi @NikitaIT 

There is a way to restructure it and extract functions to be returned as functions, not refs. However seeing that more and more people start using the lib, it would be a breaking change.

For now, if you do not like that you have to call `.value()` on a function you can do something like:
```
const query = reactive(useQuery())
query.refetch()
```

If more people would think that this is cumbersome, we can think about improving it in V2.

**Comment by jakedohm** [comment]
Just wanted to chime in that this just snagged me, I assumed I could do `query.refetch()` and couldn't figure out why that wasn't right until I found this thread.
