### ISSUE TITLE
ref and reactive options

### ISSUE THREAD

**Issue by 1saf** [DamianOsipiuk/vue-query#5]
Hey,

I noticed that if you have values which are already a `ref` the options parameter doesn't recognise a change on those values. Is there a proper way to get around this?

Example
```js
// enabled is externally changed
const enabled = ref(false);

const options = reactive({ enabled: enabled.value });

// if enabled is changed to true, the query does not fire
const q = useQuery('query', myFunction, options)
```

**Comment by onkarj422** [comment]
> Hey,
> 
> I noticed that if you have values which are already a `ref` the options parameter doesn't recognise a change on those values. Is there a proper way to get around this?
> 
> Example
> 
> ```js
> // enabled is externally changed
> const enabled = ref(false);
> 
> const options = reactive({ enabled: enabled.value });
> 
> // if enabled is changed to true, the query does not fire
> const q = useQuery('query', myFunction, options)
> ```

I have a few questions.
Why are you mixing ref & reactive?
Do options really need to be reactive as a whole?

I think this will work if you remove options variable altogether and and just pass plain object as options.
```
const q = useQuery('query', myFunction, { enabled: enabled.value });
```

**Comment by 1saf** [comment]
Heyo thanks for replying.
I'd have not used the reactive wrapper, but given the docs mentioned wrapping dynamic options in a reactive call I'd thought it fix the problem.

With the plain implementation as you've mentioned, it didn't work.

**Comment by onkarj422** [comment]
Well, checkout this [comment](https://github.com/DamianOsipiuk/vue-react-query/issues/4#issuecomment-824710363) and the discussion around it from other issue. It has the code with the use of enabled, and that's a working code. Might help you.

**Comment by DamianOsipiuk** [comment]
Hi, you might want to try something similar to this test: https://github.com/DamianOsipiuk/vue-react-query/blob/main/tests/useQuery.test.ts#L174

Basically, if you unwrap the ref for the reactive manually, it will lose reactivity, so updates would not be detected.

Let me know if it works

**Comment by 1saf** [comment]
Your example works because the reactive you check does not rely on any refs, however, for my case, I need to rely on a computed ref.

**Comment by 1saf** [comment]
> Hi, you might want to try something similar to this test: https://github.com/DamianOsipiuk/vue-react-query/blob/main/tests/useQuery.test.ts#L174
> 
> 
> 
> Basically, if you unwrap the ref for the reactive manually, it will lose reactivity, so updates would not be detected.
> 
> 
> 
> Let me know if it works

Yea this worked. Was trying to avoid wrapping the flag as a computed property but there seems no way around it.
Cheers

**Comment by DamianOsipiuk** [comment]
Hmm, I think whether you use computed, or ref should not matter. Just try passing the ref directly without unwrapping it by `value`

**Comment by 1saf** [comment]
Yeah that works as well. But for example if you would need to use it as its converse value E.g. `! some Ref` you would need to create a computed property for that right?

**Comment by DamianOsipiuk** [comment]
If you mean something like
```
const enabled = ref(false)
const options = reactive({
  enabled,
})

...

enabled.value = !enabled.value
```
It should still work

**Comment by 1saf** [comment]
Modified basic example below. The query is relying on the falsiness of enabled. In this case it would need to be a computed ref right?
```js  
setup() {
    const enabled = ref(true);
    const opts = reactive({
      retry: 0,
      staleTime: 1000,
      cacheTime: 2000,
      enabled: !enabled.value
    });

    onMounted(() => {
      setTimeout(() => (enabled.value = false), 4000);
    });

    const { isLoading, isError, isFetching, data, error, refetch } = useQuery(
      'todos',
      todoFetcher,
      opts
    );

    return { isLoading, isError, isFetching, data, error, refetch };
  }```

**Comment by DamianOsipiuk** [comment]
Hmm in this case something like this should work for you:
```
setup() {
    const opts = reactive({
      retry: 0,
      staleTime: 1000,
      cacheTime: 2000,
      enabled: false
    });

    onMounted(() => {
      setTimeout(() => (opts.enabled = true), 4000);
    });

    const { isLoading, isError, isFetching, data, error, refetch } = useQuery(
      'todos',
      todoFetcher,
      opts
    );

    return { isLoading, isError, isFetching, data, error, refetch };
  }
```

**Comment by jueinin** [comment]
> Hmm in this case something like this should work for you:
> 
> ```ts
> 
> setup() {
> 
>     const opts = reactive({
> 
>       retry: 0,
> 
>       staleTime: 1000,
> 
>       cacheTime: 2000,
> 
>       enabled: false
> 
>     });
> 
> 
> 
>     onMounted(() => {
> 
>       setTimeout(() => (opts.enabled = true), 4000);
> 
>     });
> 
> 
> 
>     const { isLoading, isError, isFetching, data, error, refetch } = useQuery(
> 
>       'todos',
> 
>       todoFetcher,
> 
>       opts
> 
>     );
> 
> 
> 
>     return { isLoading, isError, isFetching, data, error, refetch };
> 
>   }
> 
> ```
> 
> or
> 
> ```ts
> 
> setup() {
> 
>     const enabled = ref(false);
> 
>     const opts = reactive({
> 
>       retry: 0,
> 
>       staleTime: 1000,
> 
>       cacheTime: 2000,
> 
>       enabled,
> 
>     });
> 
> 
> 
>     onMounted(() => {
> 
>       setTimeout(() => (enabled.value = true), 4000);
> 
>     });
> 
> 
> 
>     const { isLoading, isError, isFetching, data, error, refetch } = useQuery(
> 
>       'todos',
> 
>       todoFetcher,
> 
>       opts
> 
>     );
> 
> 
> 
>     return { isLoading, isError, isFetching, data, error, refetch };
> 
>   }
> 
> ```

the reactive api can be more hard than react hooks🤣  sometimes,it just lost reactivity

**Comment by 1saf** [comment]
Indeed, just need to make sure to use computed properties in those scenarios.

**Comment by lizy0329** [comment]
I found that
```
// It's work √√√√√√√√√√√
const uid = ref(0);
const bid = ref(0);
const enabled = ref(false);

// share Data
const {data: shareData} = useQuery('share', () => getShareData(uid.value, bid.value), reactive({
    enabled: enabled
}));

setTimeout(() => {
  enabled.value = true
}, 1000)
```

```
// It's not work ××××××××
const uid = ref(0);
const bid = ref(0);

// share Data
const {data: shareData} = useQuery('share', () => getShareData(uid.value, bid.value), reactive({
    enabled: uid
}));

setTimeout(() => {
  uid .value = 12345
}, 1000)
```

should we code like react-query？
```
√ drop reactive options
√ enabled support like：enabled: !!uid.value && !!bid.value

const uid = ref(0);
const bid = ref(0);

// share Data
const {data: shareData} = useQuery('share', () => getShareData(uid.value, bid.value), {
    enabled:  !!uid.value && !!bid.value
});
```

**Comment by wobsoriano** [comment]
@lizy0329 I always do it like your 3rd example but something like this:

```js
const uid = ref(0);
const bid = ref(0);

// share Data
const {data: shareData} = useQuery('share', () => getShareData(uid.value, bid.value), {
    enabled: !!uid && !!bid
});

setTimeout(() => {
  uid.value = 12345
  bid.value = 45678
}, 1000)
```
