### ISSUE TITLE
How to set initial data?

### ISSUE THREAD

**Issue by reactjser** [DamianOsipiuk/vue-query#56]
In `react-query`, I can use `const {data = []} =  useQuery(...)`, since empty data is `undefined`, I want to know how to set set in `vue-query`?

**Comment by wobsoriano** [comment]
Are you talking about setting [initial query data](https://react-query.tanstack.com/guides/initial-query-data)?

**Comment by reactjser** [comment]
> Are you talking about setting [initial query data](https://react-query.tanstack.com/guides/initial-query-data)?

Thanks! It works.
