### ISSUE TITLE
TypeScript - React's JSX global namespace is being used over Vue's

### ISSUE THREAD

**Issue by ctrlplusb** [DamianOsipiuk/vue-query#57]
Hi, thanks for exposing this great library to the Vue community.

I am using `.tsx` files for my Vue project as I prefer the TypeScript safety. All was well until I installed `vue-query`. Then all my JSX broke and the error messages seem to show that the interfaces of my vue components were not matching interfaces that appeared to be inline with React's JSX definition.

I dug in a bit and my suspicions were confirmed. It appears that you are importing the React types, which inadvertently triggers the namespace collision. 

It's the first time I have experienced this with TypeScript so I have no recommendation unfortunately. I am hoping I can somehow give Vue's definitions priority.

**Comment by DamianOsipiuk** [comment]
Hi,
Does the issue happen only when you import something from `vue-query/types`? If that is the case, then I think we could try to solve it.

Also, some minimal reproduction example in codesandbox would be neat.

**Comment by DamianOsipiuk** [comment]
@ctrlplusb Should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.8.1
Let me know if it works for you.
