### ISSUE TITLE
Allow custom clients

### ISSUE THREAD

**Issue by bisubus** [DamianOsipiuk/vue-query#58]
Currently the library does the great job but is forced to use a single query client, while a client isn't granular - there are no modules like in Vuex.

In my example I needed several clients with independent cache to be available in the same hierarchy of components. Currently this requires to fully rewrite useBaseQuery and other hooks that depend on it. Considering that utils.ts is unavailable from the outside, this needs to fork the library instead of wrapping it in custom hooks. 

The suggestion is to allow multiple clients per application, this will make the library way more flexible. The only adjustment that is needed it is to inject a client through options instead of mandatory provide/inject:

```js
function useBaseQuery(options, observer) {
  const queryClient = options.queryClient ?? useQueryClient();
  ...
```

```js
function useMyQuery(options, observer) {
  return useQuery({...options, queryClient: myQueryClient}, observer);
```

This makes the library a lot more flexible. In my case `myQueryClient` couldn't be injected, but in custom hook this could be left to the discretion of a developer.

**Comment by DamianOsipiuk** [comment]
@bisubus Could you elaborate more on the use case of having multiple QueryClients in the same application?

I've seen more questions in `react-query` repo about sharing the same QueryClient between applications to leverage cache, not splitting them apart.

As for modularization you could leverage `queryKey` to get the same thing. As `queryKey` determines the caching strategy, if you prefix `queryKey` with a `module` key it would separate queries for you. Ex. `const queryKey = ['myModuleA', 'posts']`
With this, if you wrap it with a custom hook you will get cache separation. Ex:
```
function useModuleAPosts() {
  return useQuery(['moduleA', 'posts'], postsFetcher)
}

function useModuleBPosts() {
  return useQuery(['moduleB', 'posts'], postsFetcher)
}
```

Will that work for your use case?

**Comment by bisubus** [comment]
I'm trying to keys for separate cache where possible, yes. But this creates a problem if a sub-app has already been hard-coded to use global query namespace, which is my another case. Also default client options need to be merged manually in wrappers for separate modules, while this could be natively handled by using multiple clients. FWIW, I already added custom query client option with proper typing in private fork, so I could possibly commit it.

Besides clients, I'd suggest to expose util exports, currently it needs to be pasted because `parse...` functions are essential for custom query factories. Probably it's easier to include `src` for the purpose of extending which it's a common practice.

**Comment by DamianOsipiuk** [comment]
I would say that instead of passing an instance of `queryClient` to the hook options, we could pass just a context key under which this query client would be available.
So the API would allow you to use multiple `useQueryProvider` with different keys.

```js
import { defineComponent } from "vue";
import { useQueryProvider } from "vue-query";

export default defineComponent({
  name: "App",
  setup() {
    useQueryProvider({}, 'my-client-1');
    useQueryProvider({}, 'my-client-2');
    ...
  },
});
```

and then pass those via options

```js
useQuery({...options, queryClientKey: 'my-client-1'});
```

The reason for that is `DevTools`. If you pass `queryClient` directly to hook, DevTools would not be able to subscribe to changes. But if it's provided via Vue context, the only thing you need is it's key.
This would also allow providing `multiple` keys to `DevTools`, to which it should subscribe and allow to toggle through them.

**Comment by bisubus** [comment]
The support for devtools is a good point, identifying clients by keys looks like a proper way to do this. It's true that hooks may need queryClientKey instead of queryClient for this reason because a client needs to be a provider any way.

Then a corner case with accessing a client outside Vue component hierarchy could be solved by either allowing to provide a client instead of client options:

```js
useQueryProvider(new QueryClient(...));
useQueryProvider(new QueryClient(...), 'CUSTOM_CLIENT');
```

This currently can be handled, but depends on useQueryProvider implementation:

```js
provide(VUE_QUERY_CLIENT, {...});
provide(VUE_QUERY_CLIENT + ':CUSTOM_CLIENT', {...});
```

**Comment by DamianOsipiuk** [comment]
@bisubus I think we can go with 1st method.
You either provide QueryClient config or QueryClient itself. The second parameter would be a `suffix` to the original key that is used to provide it in the context.

I have started working on it in https://github.com/DamianOsipiuk/vue-query/pull/65

**Comment by bisubus** [comment]
@DamianOsipiuk Looks great so far. What do you think about exposing utils exports or the whole src to provide parseFilterArgs, etc for custom hooks?

**Comment by DamianOsipiuk** [comment]
@bisubus I do not see the reason to expose utils. Those are the internal functions to handle hooks parameters overloads.
Could you provide a use case for it?

**Comment by bisubus** [comment]
@DamianOsipiuk The case is to normalize options in custom hooks while keeping the original signature of a hook, e.g. merge options and prepend keys:

```
const myHook = (arg1, arg2, arg3) => {
    const options = parseQueryArgs(arg1, arg2, arg3);
    // prepend options.queryKey
    return useQuery({ ...myOptions, ...options, queryKey });
  });
