### ISSUE TITLE
More generic SSR support

### ISSUE THREAD

**Issue by frandiox** [DamianOsipiuk/vue-query#62]
Hi, thanks for this library! I'm maintaining a couple of packages for SSR with Vite and I'm interested in supporting `vue-query`. I see the SSR support is experimental so I would like to add some feat requests to make it easier to integrate with other tools.

It would be great if we could create and provide a Query Client outside of a component, just like any other Vue library that is installed when creating the app:

```js
const queryClient = new QueryClient({ ... })

app.use(queryClient) // This would use queryClient.install method to run `app.provide(..., queryClient)`
```

Everything else could probably work in the same way, but this gives us the ability to export this created client to pass it to any SSR tool we need (for calling`hydrate` or `dehydrate`), which are normally outside of component scopes.
Thanks!

**Comment by DamianOsipiuk** [comment]
Hi,
Thanks for this idea.
Since `QueryClient` is actually inherited from `react-query/core` i do not want to modify it or create a wrapper.

But I think we can achieve the same functionality via the following API:
```js
import { vueQueryPlugin, QueryClient } from 'vue-query';

// Created manually
const queryClient = new QueryClient(queryClientConfig)

app.use(vueQueryPlugin, queryClient)
```

where `vueQueryPlugin` will be responsible for 

```js
queryClient.mount();
app.provide(VUE_QUERY_CLIENT, queryClient);
```

What I'm thinking though is if we could bake in both `useNuxtQueryProvider` and `useQueryProvider` into a single plugin.
I'm only worried if ex. `nuxt` plugin would properly separate user sessions. Cause providing QueryClient globally could mix caches for multiple users with will be a massive issue.

**Comment by frandiox** [comment]
@DamianOsipiuk Thanks, this could work as well.

And it's true what you say. I'm not very familiar with Nuxt but there should be somewhere that runs only once per request and that can re-create the client, right? Otherwise, I guess a "useQueryProvider" that runs inside the root component would also be necessary 🤔

**Comment by DamianOsipiuk** [comment]
@frandiox Unfortunately plugins for Vue 2 do not support the `app.provide` on `install` method.
The composition API plugin does not provide it either.

Therefore to support both Vue versions, we will have to come up with some kind of a hack or add a plugin that would work only for Vue 3, which is not ideal.

As for now, I think that solution proposed in https://github.com/DamianOsipiuk/vue-query/issues/58 would work for your use case.

**Comment by frandiox** [comment]
Ah, I see. I guess it still requires using the hook within a component, but at least it should be possible to create the client somewhere else and pass it by using some sort of global variable.
Thanks for checking it.

**Comment by DamianOsipiuk** [comment]
@frandiox You can try https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.9.0

**Comment by frandiox** [comment]
@DamianOsipiuk So, as far as I understand, an example using `vite-ssr` or `vitedge` would look like this:

```js
// main.js
import App from './App.vue'
import viteSSR from 'vite-ssr/vue'
import { QueryClient } from 'vue-query'
import { hydrate, dehydrate } from 'vue-query/ssr'

export default viteSSR(
  App,
  {
    routes: [],
    transformState(state, defaultTransformer) {
      if (import.meta.env.SSR) {
        state.vueQuery = dehydrate(state.vueQuery)
      }

      return defaultTransformer(state)
    },
  },
  ({ app, initialState }) => {
    const client = new QueryClient()
    hydrate(client, initialState.vueQuery)
    initialState.vueQuery = client
  }
)

```

```vue
<script>
// App.vue
import { useContext } from 'vite-ssr'
import { useQueryProvider } from 'vue-query'

export default {
  setup() {
    const { initialState } = useContext()
    useQueryProvider(initialState.vueQuery)
  },
}
</script>
```
---

However, this crashes with error `Could not resolve "@nuxtjs/composition-api"` since the `vue-query/ssr` module is importing Nuxt-related stuff. I've tried importing from `vue-query/ssr/hydration` but that's not exposed, unfortunately.
Can the Nuxt stuff be separated from the agnostic hydration?

Thanks!

**Comment by wobsoriano** [comment]
> @DamianOsipiuk So, as far as I understand, an example using `vite-ssr` or `vitedge` would look like this:
> 
> ```js
> // main.js
> import App from './App.vue'
> import viteSSR from 'vite-ssr/vue'
> import { QueryClient } from 'vue-query'
> import { hydrate, dehydrate } from 'vue-query/ssr'
> 
> export default viteSSR(
>   App,
>   {
>     routes: [],
>     transformState(state, defaultTransformer) {
>       if (import.meta.env.SSR) {
>         state.vueQuery = dehydrate(state.vueQuery)
>       }
> 
>       return defaultTransformer(state)
>     },
>   },
>   ({ app, initialState }) => {
>     const client = new QueryClient()
>     if (!import.meta.env.SSR) hydrate(client, initialState.vueQuery)
>     initialState.vueQuery = client
>   }
> )
> ```
> 
> ```
> <script>
> // App.vue
> import { useContext } from 'vite-ssr'
> import { useQueryProvider } from 'vue-query'
> 
> export default {
>   setup() {
>     const { initialState } = useContext()
>     useQueryProvider(initialState.vueQuery)
>   },
> }
> </script>
> ```
> 
> However, this crashes with error `Could not resolve "@nuxtjs/composition-api"` since the `vue-query/ssr` module is importing Nuxt-related stuff. I've tried importing from `vue-query/ssr/hydration` but that's not exposed, unfortunately.
> Can the Nuxt stuff be separated from the agnostic hydration?
> 
> Thanks!

Same problem here https://github.com/DamianOsipiuk/vue-query/discussions/66

**Comment by DamianOsipiuk** [comment]
Should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.10.0
