### ISSUE TITLE
Usage with jest

### ISSUE THREAD

**Issue by sem4phor** [DamianOsipiuk/vue-query#63]
Hi!

I wanted to test a shallow mounted component with jest and vue-test-utils@next and as you could imagine I run into

`No queryClient found in Vue context, use 'useQueryProvider' to set one in the root component.`

Any ideas how to approch this issue besides writing a jest mock?

**Comment by DamianOsipiuk** [comment]
Hi,
If you do not want to incorporate jest mock, you can write a tiny plugin wrapper in your project.
Then when the library will expose its own plugin, you can just change the import without additional changes.

Something like this should work for you:
```js
import { VUE_QUERY_CLIENT, QueryClient } from 'vue-query';

export const vueQueryPlugin = {
  install: (app, options) => {
    const queryClient = new QueryClient(options);
    app.provide(VUE_QUERY_CLIENT, queryClient)
  }
}
```
and then call it in your test file
```js
Vue.use(vueQueryPlugin)
```

**Comment by sem4phor** [comment]
Thank you so much. I also figured out a workaround without a plugin by providing the QueryClient in a jest setup file (which i needed eitherwise)

```
// setup.js
import { QueryClient } from 'vue-query';
import { config } from '@vue/test-utils';
config.global.provide= {
  VUE_QUERY_CLIENT: new QueryClient()
};
```

**Comment by sem4phor** [comment]
So did anyone actually unit test a vue-query component?

i have a component sth like this:
```
const queryFunction = () => new Promise((resolve) => {
  setTimeout(() => resolve([]), 300);
});
...
setup() {
  const { isLoading } = useQuery(queryFunction );
}
...
``` 

and a test like this:
```
const wrapper = shallowMount(Component);
test('loading', async () => {
    console.log(wrapper.vm.isLoading);
    await flushPromises();
    console.log(wrapper.vm.isLoading);
})
```

isLoading stays `true` :/ any ideas?

**Comment by DamianOsipiuk** [comment]
Your `queryFunction` has `300` ms delay, so you need to wait for that amount in your test.
`flushPromises()` implementation usually has `0` ms delay

**Comment by sem4phor** [comment]
ah yeah sorry I updated the code and used a normal promise without timeouts and even a synchronous function they both do not work.

**Comment by DamianOsipiuk** [comment]
> ```
> const queryFunction = () => new Promise((resolve) => {
>   resolve([]);
> })
> /**
> const queryFunction = () => [];
> */
> ...
> setup() {
>   const { isLoading } = useQuery(queryFunction );
> }
> ...
> ```
`useQuery` has 3 overloads:
- useQuery(options)
- useQuery(queryKey, options)
- useQuery(queryKey, queryFn, options)
Where `queryKey` is always needed for caching purposes and can be passed via options.

Try: `const { isLoading } = useQuery('foo', queryFunction );`

**Comment by sem4phor** [comment]
Yeah my code above was meant more like pseudo code. In the actual code which I can not share here I set up everything correct, the query and so on I do not get any compile errors. It just seems like the query is not triggering in the jest environment.

**Comment by DamianOsipiuk** [comment]
@sem4phor Could you try to mock the `onUnmounted` method from Vue in your test and see if it helps?
I believe it might be an issue that this method is called prematurely. As a result hooks are unsubscribing from changes.
Something along:
```
const vue = jest.requireActual("vue");

module.exports = {
  ...vue,
  onUnmounted: jest.fn(),
};
```

If that helps, then we would have to figure out why it's called before the test ends.

**Comment by DamianOsipiuk** [comment]
@sem4phor Did you manage to solve the issue?

**Comment by sem4phor** [comment]
I tested your suggestion. unmounted is not called in the test scenario

**Comment by sem4phor** [comment]
I created a reproduction repository https://github.com/sem4phor/vue-query-jest when you run `npm test`you can see that the console logs from the HelloWorld component are not logged.

**Comment by DamianOsipiuk** [comment]
@sem4phor 
I took a look at the reproduction repository and noticed few issues:
1. you do not mock network requests in your tests
2. you do not use something like `node-fetch` for jest environment
3. you do not wait for actual request to be done before second assertion

To fix it you could:
- mock `fetch` to fix all the issues.
- install `node-fetch` as dev dependency and assign it via `import fetch from "node-fetch"; global.fetch = fetch;` in `setup.js`. This will solve the issue with jest throwing an error that `fetch` is not defined. But do not solve third issue.
- **(This is not recommended as it will slow down your tests)** If you do not mock network request, you have to actually wait for it. Ex by implementing your own `flushPromises` that would wait for ex. 100ms before next assertion.

Also you should disable retries on failure (this will make the second issue from above clearly visible) in vue-query by providing config to `QueryClient`. Ex from your repo:
```
config.global.provide = {
  [VUE_QUERY_CLIENT]: new QueryClient({
    defaultOptions: {
      queries: {
        retry: false,
      },
    },
  }),
};
```

If you fix those issues, tests would work as intended.

**Comment by sem4phor** [comment]
I installed jest fetch mock and it worked. Thank you for clearification. 

I just had a look at the react-query docs and the retry thing is actually documented there. So I am closing this issue :)

**Comment by petitkriket** [comment]
> @sem4phor I took a look at the reproduction repository and noticed few issues:
> 
> 1. you do not mock network requests in your tests
> 2. you do not use something like `node-fetch` for jest environment
> 3. you do not wait for actual request to be done before second assertion
> 
> To fix it you could:
> 
> * mock `fetch` to fix all the issues.
> * install `node-fetch` as dev dependency and assign it via `import fetch from "node-fetch"; global.fetch = fetch;` in `setup.js`. This will solve the issue with jest throwing an error that `fetch` is not defined. But do not solve third issue.
> * **(This is not recommended as it will slow down your tests)** If you do not mock network request, you have to actually wait for it. Ex by implementing your own `flushPromises` that would wait for ex. 100ms before next assertion.
> 
> Also you should disable retries on failure (this will make the second issue from above clearly visible) in vue-query by providing config to `QueryClient`. Ex from your repo:
> 
> ```
> config.global.provide = {
>   [VUE_QUERY_CLIENT]: new QueryClient({
>     defaultOptions: {
>       queries: {
>         retry: false,
>       },
>     },
>   }),
> };
> ```
> 
> If you fix those issues, tests would work as intended.


When setting the client using provide() like in the example above.

I was wondering, would someone know how to access the client `queryClient.clear()` method between tests to insure that the tests stay independant between each other.


```
beforeEach(() => {
// I wish I could access the provide() client from the test suite to clean the cache between tests
    queryClient.clear();
});
```
