### ISSUE TITLE
Reactive options is behaving weird?

### ISSUE THREAD

**Issue by mirabledictu** [DamianOsipiuk/vue-query#67]
Hello, I have a simple example where I want to disable the query when an input is undefined or an empty string. Here's my code:

```javascript
// api.js
import { reactive } from "vue";
import { useQuery } from "vue-query";

const fetcher = async (id) => {
  const res = await fetch("https://jsonplaceholder.typicode.com/todos/" + id);
  const data = await res.json();
  return data;
};

export function useGetTodo(id) {
  const key = reactive(["todo", id]);
  const options = reactive({
    enabled: !!id
  });

  return useQuery(key, () => fetcher(id.value), options);
}
```

```html
// Component.vue
<template>
  <input type="text" v-model="id" />
  <div v-if="isLoading">Loading...</div>
  <div v-else>{{ JSON.stringify(data) }}</div>
</template>

<script setup>
import { ref } from "vue";
import { useGetTodo } from "../api";

const id = ref("");

const { data, isLoading } = useGetTodo(id);
</script>
```

First thing I expect here is that on first load, since the input is empty, the query will not run. The options is inside the `reactive` property and to my surprise, if I am missing something, it is still running.

You can check it here https://codesandbox.io/s/vue-query-reactive-options-forked-nslhg

**Comment by mirabledictu** [comment]
So I tried logging `const id = ref("");` with

```js
console.log(!!id)
```

and it actually returns true. To make it return `false`, it needs to do `console.log(!!id.value)`.

How do we go about this?

**Comment by DamianOsipiuk** [comment]
So i would go with something like:
```js
export function useGetTodo(id) {
  const enabled = computed(() => Boolean(id.value));
  const key = reactive(["todo", { id }]);
  const options = reactive({
    enabled
  });

  return useQuery(key, () => fetcher(id.value), options);
}
```
Notice `computed` property and key that includes `id` as an object, not directly in array.

The reason for this is that `ref` is an object actually, not a value. So doing `!!{}` will always return true.
Also reactive on arrays have some caveats, so passing `id` in the object will work better.

More concise:
```js
export function useGetTodo(id) {
  const options = reactive({
    queryKey: ["todo", { id }],
    queryFn: () => fetcher(id.value),
    enabled: computed(() => Boolean(id.value))
  });

  return useQuery(options);
}
```

**Comment by mirabledictu** [comment]
> So i would go with something like:
> 
> ```js
> export function useGetTodo(id) {
>   const enabled = computed(() => Boolean(id.value));
>   const key = reactive(["todo", { id }]);
>   const options = reactive({
>     enabled
>   });
> 
>   return useQuery(key, () => fetcher(id.value), options);
> }
> ```
> 
> Notice `computed` property and key that includes `id` as an object, not directly in array.
> 
> The reason for this is that `ref` is an object actually, not a value. So doing `!!{}` will always return true.
> Also reactive on arrays have some caveats, so passing `id` in the object will work better.
> 
> More concise:
> 
> ```js
> export function useGetTodo(id) {
>   const options = reactive({
>     queryKey: ["todo", { id }],
>     queryFn: () => fetcher(id.value),
>     enabled: computed(() => Boolean(id.value))
>   });
> 
>   return useQuery(options);
> }
> ```

Oh I like the query object instead of parameters thing! That worked. Vue reactivity is weird in times like this lol thank you

**Comment by mirabledictu** [comment]
Oh btw, this
