### ISSUE TITLE
Suspense not working in SSR

### ISSUE THREAD

**Issue by frandiox** [DamianOsipiuk/vue-query#70]
Hi! Looks like suspense is always undefined during SSR?
This is the official example: https://txnjc.sse.codesandbox.io/ , but its rendered HTML doesn't contain the todos (check the view-source tool).

After setting up Suspense in `App.vue`, I'm trying the following in a component:

```js
   async setup() {
    const { data, suspense } = useQuery('todos', fetcher)

    const p = suspense()
    console.log(p)
    await p

    return { data }
  }
```

It prints `undefined` in the server and a promise in the browser.

My end goal is just getting a promise to await in the server for SSR:

```js
  setup() {
    const { data, suspense } = useQuery('todos', fetcher)

    onServerPrefetch(() => suspense())

    return { data }
  }
```

Any idea how to do this without too much boilerplate? (simplified version of useQueryClient + prefetchQuery)

**Comment by DamianOsipiuk** [comment]
Hi,
I think we could change the following https://github.com/DamianOsipiuk/vue-query/blob/main/src/vue/useBaseQuery.ts#L65 to always return the `fetchOptimistic` promise.
Condition is there currently to check whether the component was wrapped with the `Suspense` component, but I guess it's not entirely needed.
Not sure though if `suspense()` will be a good name for it after removing the condition.

**Comment by frandiox** [comment]
@DamianOsipiuk I think that would be nice. I use something like this in a private project and we call it "loading": `const { data,  loading } = useQuery(xxx)`.  Then you can do `await loading()` when needed. Just an idea for the naming but I guess there are better.

**Comment by DamianOsipiuk** [comment]
@frandiox You can try with https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.10.1

**Comment by frandiox** [comment]
@DamianOsipiuk works great, thanks!
Would you accept a PR adding docs on how to use vue-query with vite-ssr?

**Comment by DamianOsipiuk** [comment]
Yup, go for it 👍
