### ISSUE TITLE
UseQueryOptions interface is not exposed

### ISSUE THREAD

**Issue by FLKWSKI** [DamianOsipiuk/vue-query#71]
Hello! 
While using this awesome library, I noticed that some useful interfaces like `UseQueryOptions` or `UseMutationOptions` are not exposed.

I was creating wrapper functions for my queries/mutations, and wanted to add an `options` parameter to override query options:
```typescript
function useMyQuery (options?: UseQueryOptions) {
  return useQuery(
    'my-query', 
    async () => fetch('/api'),
    {
      retry: false,
      ...options
    }
  );
}
```

Unfortunately this is not possible, because the interface `UseQueryOptions` is not exposed by `vue-query`.
I've tried importing it directly from `react-query`, but that caused some issues ("_Cannot find module 'react' or its corresponding type declarations._").

I've also tried to add the following line to [/src/index.ts](/DamianOsipiuk/vue-query/blob/main/src/index.ts):
```typescript
export { UseQueryOptions, UseMutationOptions } from "react-query/types/react/types";
```

This worked without any issues and I believe that would be a decent solution.
If you agree, I'd be happy to create a PR :slightly_smiling_face: 
Maybe it would be also good to expose all other interfaces and types in `react-query/types/react/types` as well.

**Comment by DamianOsipiuk** [comment]
Hello.
You could try to import it from `vue-query/types`. This re-exports types from react-query (https://github.com/DamianOsipiuk/vue-query/blob/main/types/index.d.ts)

**Comment by FLKWSKI** [comment]
My bad.. I did not see that.
Thank you for fast reply.
