### ISSUE TITLE
Vue 2.x without composition api?

### ISSUE THREAD

**Issue by hoangvu12** [DamianOsipiuk/vue-query#72]
So I just look at the example, I can see it's using composition API, I'm new to Vue, and I don't have time to rewrite my codebase to composition api. (maybe I spell wrong). Is there any way to use this library? I'm in love with `react-query` so I'd love to use another version of it. Thank you :)

**Comment by wobsoriano** [comment]
You need composition api to use the composables 😁

**Comment by jueinin** [comment]
@hoangvu12 `npm install @vue/composition-api`. you can follow this [repo](https://github.com/vuejs/composition-api)

**Comment by hoangvu12** [comment]
> You need composition api to use the composables 😁

Oh, well I'm learning using it. Thanks

**Comment by hoangvu12** [comment]
> @hoangvu12 `npm install @vue/composition-api`. you can follow this [repo](https://github.com/vuejs/composition-api)

Thank you ;D, I'm amazed by how fast you guys reply me
