### ISSUE TITLE
How to implement `useInfiniteQueries`?

### ISSUE THREAD

**Issue by hoangvu12** [DamianOsipiuk/vue-query#73]
I've spent few hours just to try implementing infinite scrolling using `useInfiniteQueries`, Can anyone just give me example about it? Thank you

**Comment by wobsoriano** [comment]
Here's an example using rick and morty api https://github.com/wobsoriano/vite-plugin-ssr-vue-query/blob/master/pages/characters/index.page.vue

**Comment by hoangvu12** [comment]
> Here's an example using rick and morty api https://gist.github.com/wobsoriano/c9954fdf3a49c2314475c747d201d31b

Thank you, I wonder if I can use state instead of `nextPage` from API response?

![image](https://user-images.githubusercontent.com/68330291/131611688-53b383d8-c67d-428f-826e-028a1b558dc7.png)

**Comment by wobsoriano** [comment]
Hmm I haven't tried that but I think it should work. Try to return the value too

```ts
getNextPageParam() {
  page.value += 1
  return page.value
}
```

**Comment by hoangvu12** [comment]
> Hmm I haven't tried that but I think it should work. Try to return the value too
> 
> ```ts
> getNextPageParam() {
>   page.value += 1
>   return page.value
> }
> ```

_No it didn't works, somehow `getNextPageParam` executed multiple times.

Well I actually can just return `nextPage` in my API query function. That workaround should works. Thank you.

**Comment by wobsoriano** [comment]
> > Hmm I haven't tried that but I think it should work. Try to return the value too
> > ```ts
> > getNextPageParam() {
> >   page.value += 1
> >   return page.value
> > }
> > ```
> 
> _No it didn't works, somehow `getNextPageParam` executed multiple times.
> 
> Well I actually can just return `nextPage` in my API query function. That workaround should works. Thank you.

That's how you should do it
