### ISSUE TITLE
setQueryData does not update the state

### ISSUE THREAD

**Issue by xiaosasori** [DamianOsipiuk/vue-query#78]
Hi!

I wanted to update cached data by using `useQueryClient`'s `setQueryData` method. But the state returned from `useQuery` didn't get updated by updating the cache.

Could anyone show me a proper way to sync the state after updating the cache?

## Reproduction link
[codesandbox.io](https://codesandbox.io/s/brave-turing-ur4or?file=/src/components/HelloWorld.vue)

## Steps to reproduce
Clicking on `Update` button

## What is expected?
`data.title` should get updated

## What is actually happening?
The `cache` get updated. But the state does not

**Comment by DamianOsipiuk** [comment]
Hi,

The solution to your problem would be to overwrite the whole object, not mutating a single property.
```
queryClient.setQueryData("post", (d) => {
    return {
      ...d,
      title: "updated"
    };
  });
```

I think this is due to Vue watcher being shallow by default for refs. But I might be wrong.
