### ISSUE TITLE
Adding generic types to useQueries

### ISSUE THREAD

**Issue by voxivoid** [DamianOsipiuk/vue-query#80]
Would it be possible to allow passing generic types to `UseQueryOptions` and `UseQueryResult` from `useQueries`? Not allowing this causes it to be defaulted to unknown which means that we will not have the results typed.

https://github.com/DamianOsipiuk/vue-query/blob/main/src/vue/useQueries.ts#L10-L11

**Comment by DamianOsipiuk** [comment]
Hi,
In theory it should be possible, but in reality you have an array in which each entry would be potentially a different type.
So you would have to provide generic for each element of the array separately.
If you can come up with typings that would work and could potentially be inferable, i would gladly integrate them in the project.

**Comment by voxivoid** [comment]
https://github.com/tannerlinsley/react-query/pull/2634

actually it seems that some work is already being made on the react-query side to support this. hopefully it will be something that we can adopt when merged 🤞

**Comment by DamianOsipiuk** [comment]
@voxivoid @potb During my testing, I found that types for TS < 4.1 are already broken. Therefore i have just updated the docs with recommended TS version of v4.1 or greater.
If there will be high demand for lower TS versions we can think of finding when that got broken and try to fix it.
