### ISSUE TITLE
type check and vue-demi exported member

### ISSUE THREAD

**Issue by ItMaga** [DamianOsipiuk/vue-query#83]
![issue](https://user-images.githubusercontent.com/51162910/134888320-f9b81da8-ffe8-49dc-8c7c-9a6404fcbce1.png)

It can be fixed somehow or cannot do anything about it? I wouldn't like to resort to `skipLibCheck`:)

version 1.10.1

**Comment by DamianOsipiuk** [comment]
Hi, I need to check the bundle if some react reference slipped again into the repo.
It should not happen, as i have fixed that before.

**Comment by DamianOsipiuk** [comment]
Should be fixed in https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.11.2
Could you verify that this fixes your issue?

**Comment by ItMaga** [comment]
Yes, it has fixed the issue. 
Thank you for the quick response!
