### ISSUE TITLE
reactive as queryKey

### ISSUE THREAD

**Issue by zynth17** [DamianOsipiuk/vue-query#93]
is it possible to make reactive queryKey instead of ref we use reactive?

**Comment by Djaangoo** [comment]
I have example in Vue-property-decorator

```ts
userContext = setup(() => {
      const queryKeys = reactive(['userData', this.userId])
      
      const changeId = (id: string) => {
          queryKeys[1] = id;
      }
      const { isSuccess, data, isLoading, isError } = useQuery<IUser, AxiosError>(queryKeys, () => {
        return UserService.getUser(this.userId);
      });
      return { isSuccess, data, isLoading, isError, changeId };
    }
  });
```

**Comment by zynth17** [comment]
> I have example in Vue-property-decorator
> 
> 
> 
> ```ts
> 
> userContext = setup(() => {
> 
>       const queryKeys = reactive(['userData', this.userId])
> 
>       
> 
>       const changeId = (id: string) => {
> 
>           queryKeys[1] = id;
> 
>       }
> 
>       const { isSuccess, data, isLoading, isError } = useQuery<IUser, AxiosError>(queryKeys, () => {
> 
>         return UserService.getUser(this.userId);
> 
>       });
> 
>       return { isSuccess, data, isLoading, isError, changeId };
> 
>     }
> 
>   });
> 
> ```

sorry my bad. i mean the variable inside that reactive key. instead of ref can we use reactive? since i got so many variable for my fetching, it will be good to have reactive object instead of passing it one by one.

**Comment by ItMaga** [comment]
> > I have example in Vue-property-decorator
> > ```ts
> > userContext = setup(() => {
> > 
> >       const queryKeys = reactive(['userData', this.userId])
> > 
> >       
> > 
> >       const changeId = (id: string) => {
> > 
> >           queryKeys[1] = id;
> > 
> >       }
> > 
> >       const { isSuccess, data, isLoading, isError } = useQuery<IUser, AxiosError>(queryKeys, () => {
> > 
> >         return UserService.getUser(this.userId);
> > 
> >       });
> > 
> >       return { isSuccess, data, isLoading, isError, changeId };
> > 
> >     }
> > 
> >   });
> > ```
> 
> sorry my bad. i mean the variable inside that reactive key. instead of ref can we use reactive? since i got so many variable for my fetching, it will be good to have reactive object instead of passing it one by one.

If I understand you correctly, you can use ref your object inside reactive

```ts
const yourObject = ref({});
const queryKey = reactive(['queryKey', { yourObject }])

const { data, isLoading } = useQuery(queryKey, fetcher);
```

**Comment by DamianOsipiuk** [comment]
> is it possible to make reactive queryKey instead of ref we use reactive?

@zynth17 
Hi, yes you can. But you have to make sure that you do not overwrite the whole reactive object.
Ex. you CAN'T do this:
```ts
const params = reactive({a: 1, b: 2})
const q = useQuery(['myQuery', params], ...)
const onClick = () => {
  params = calculateNewParams()
}
```

But you can for example do this:
```ts
const params = reactive({a: 1, b: 2})
const q = useQuery(['myQuery', params], ...)
const onClick = () => {
  params.a = params.a + 1;
}
```

Example sandbox: https://codesandbox.io/s/broken-pond-bwmt0?file=/src/Post.vue

**Comment by zynth17** [comment]
> > is it possible to make reactive queryKey instead of ref we use reactive?
> 
> @zynth17 Hi, yes you can. But you have to make sure that you do not overwrite the whole reactive object. Ex. you CAN'T do this:
> 
> ```ts
> const params = reactive({a: 1, b: 2})
> const q = useQuery(['myQuery', params], ...)
> const onClick = () => {
>   params = calculateNewParams()
> }
> ```
> 
> But you can for example do this:
> 
> ```ts
> const params = reactive({a: 1, b: 2})
> const q = useQuery(['myQuery', params], ...)
> const onClick = () => {
>   params.a = params.a + 1;
> }
> ```
> 
> Example sandbox: https://codesandbox.io/s/broken-pond-bwmt0?file=/src/Post.vue

thankyou so much!
