### ISSUE TITLE
useQueries still executes if each query's enabled is set to false

### ISSUE THREAD

**Issue by rmwever** [DamianOsipiuk/vue-query#94]
Hi there, thanks for your hard work on this library! It's proved very useful to me.

I'm trying out **useQueries** for the first time today and it seems that it acts in a way that I did not anticipate. Even if the `enabled` property for the query is set to false, then the API is still called.

Please check out my sandbox here: https://codesandbox.io/s/musing-scott-91n4r?file=/src/App.vue 

Is this expected? Or should I be disabling this in another way?

**Comment by DamianOsipiuk** [comment]
@rmwever Hi, looking at the sandbox it seems that everything is working as intended.
Queries are added to the QueryClient but are not executed.
You can open you browser devtools with network tab open and verify that no network request is made when button is clicked.
Then change `enabled` property to true on your queries and check that now 3 network requests are sent.

**Comment by rmwever** [comment]
Yes, I see that. Very odd, must have been a cache issue!
