### ISSUE TITLE
Handing fetched data as a prop

### ISSUE THREAD

**Issue by RoryCombe** [DamianOsipiuk/vue-query#95]
Hi, first thanks for making this - I'm new to Vue and really missed React Query and how simple it made data fetching in React. Vue Query so far has been amazing.

I have a question rather than an issue: in my app I fetch data with `useQuery` (all good) and then pass that data as a prop to a child component, the child component however never updates. It seems something has been lost and is no longer reactive. Do I need to always add `computed` properties everywhere to tie this together? I've tried using keys on the component to force an update, but that also went nowhere.

I made a small repo demonstrating what I am trying to do in a bigger app:
https://codesandbox.io/s/vigilant-leaf-nzk5w

Any help would be appreciated as I've been hung up on this for weeks trying to figure it out 🙏🏼

**Comment by lizy0329** [comment]
I try is OK?
![image](https://user-images.githubusercontent.com/9499272/144561877-6b0a8cf3-d82b-4765-9a2a-ae8e21356aa3.png)
![image](https://user-images.githubusercontent.com/9499272/144561908-07ed406a-af36-4a2a-8d60-9a264f5a1dc7.png)

**Comment by DamianOsipiuk** [comment]
Hi @RoryCombe,

Not entirely sure what you want to achieve, but as @lizy0329 demonstrated, if you add a `button` with `@click` function that increments your `id.value` in `List.vue`, it would update the data properly.
Just make sure not to overwrite `ref` or `reactive`, but update the value.

If you want to achieve something else, please let me know.
