### ISSUE TITLE
Why we need to add reactive in Dependent Queries?

### ISSUE THREAD

**Issue by lizy0329** [DamianOsipiuk/vue-query#96]
```
const {data: tasksData, isFetching: isFetchingTasks} = useQuery(
    reactive(['mytask', {tabActive}]),
    () => getMyTaskList(route.query.appcode, tabActive.value),
    reactive({
        enabled: computed(() => Boolean(String(tabActive.value))),
        keepPreviousData: true
    })
);
```

queryKey queryOptions should reactive with built-in?

```
useQuery(queryKey: Reactive<QueryKey>) 
```

**Comment by DamianOsipiuk** [comment]
Hi @lizy0329,
Could you elaborate more on what do you mean?

If you mean about improving types to force user to pass `reactive` properties, we could do this, but it's not always necessary.
If you mean that vue-query could convert passed prop to reactive, I do not think this will work, as if it will be converted inside `useQuery` hook, it would not see the updates you make outside of it.

**Comment by lizy0329** [comment]
In my case: I have a tab component, so I write the code naturally.
![image](https://user-images.githubusercontent.com/9499272/144699691-32cde3c8-a1e4-48ab-be33-befdf3dd126b.png)

```
const tabActive = ref(0)
const {data: tasksData, isFetching: isFetchingTasks} = useQuery(
    ['act_mytask', {tabActive}],
    () => getMyTaskList(route.query.app_code, tabActive.value),
    {
        keepPreviousData: true
    }
);
```
But is not work until I check many issus
`reactive(['act_mytask', {tabActive}])` is work

there have any method to drop the `reactive` ?

**Comment by DamianOsipiuk** [comment]
I do not think that there is currently a different way of doing this, unless I've missed some clever way of doing it.

Nevertheless since react-query is currently working on [v4 which will introduce breaking changes](https://github.com/tannerlinsley/react-query/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4), it's a good time to revisit the API and maybe fix some inconsistencies.

This could also be a good time to force `Reactive<options>` via typescript. Not sure though if it would be a proper way to do it, and I would love to get a bit more feedback from other users.

**Comment by jueinin** [comment]
> I do not think that there is currently a different way of doing this, unless I've missed some clever way of doing it.
> 
> 
> 
> Nevertheless since react-query is currently working on [v4 which will introduce breaking changes](https://github.com/tannerlinsley/react-query/issues?q=is%3Aopen+is%3Aissue+milestone%3Av4), it's a good time to revisit the API and maybe fix some inconsistencies.
> 
> 
> 
> This could also be a good time to force `Reactive<options>` via typescript. Not sure though if it would be a proper way to do it, and I would love to get a bit more feedback from other users.

maybe it's not always possible, in most case, i just pass a const string as querykey

**Comment by DamianOsipiuk** [comment]
According to https://github.com/tannerlinsley/react-query/issues/2919 you would not be able to pass a plain string anymore.
For consistency reasons `queryKey` will always be an array.
Nevertheless i see use-cases, where you do not necessarily need reactive keys, therefore enforcing it on user would introduce bad DX.

Maybe a better idea would be to introduce `eslint` rule to show violations if you pass a `ref` to non-reactive array or object.

**Comment by DamianOsipiuk** [comment]
@lizy0329 Thanks to great work of @aantipov you should be able to skip reactive wrappers now for both `queryKey` (with exception of deeply nested refs) and `queryOptions` :tada: 

You could try following version: https://github.com/DamianOsipiuk/vue-query/releases/tag/v1.17.0

**Comment by lizy0329** [comment]
This is a fantastic update that will help vue-query's ease of use to the next level! Thanks to great work of @aantipov
