### ISSUE TITLE
Suggested way of accessing queries from Vue Router navigation guards? (Vue 2/VueRouter 3)

### ISSUE THREAD

**Issue by kculmback** [DamianOsipiuk/vue-query#97]
When trying to access a query within the `router.beforeEach` method, we get the following error: `Error: vue-query hooks can only be used inside setup() function.`.

Is there a suggested way to be able to access queries when using Vue Router?

The main option I've come up with is syncing some data to the Vuex store via a query's `onSuccess` hook. Not ideal, but it could technically work.

**Comment by DamianOsipiuk** [comment]
Hi @kculmback,

You could create the QueryClient instance before using `useQueryProvider` as some kind of singleton, and then access it from any part of your app as a regular JS object.

```ts
// your query client singleton module that will always return the same instance
const myClient = new QueryClient(queryClientOptions);
export default myClient;

// Your application entrypoint
import myClient from './your-singleton-module'
useQueryProvider(myClient);

// your router functions
import myClient from './your-singleton-module'
myClient.prefetchQuery('key1', key1Fetch);
```

**Comment by kculmback** [comment]
Ah this is perfect, thank you!

**Comment by ortonomy** [comment]
this works to be able to make a fetch (obviously the client will not miss executing) but once I subscribe to the query in my app, it's not like the prefetch never happened. and it calls it request immediately.

**Comment by rhclayto** [comment]
I'm not sure I understand how to use these instructions here. Could someone kindly give a fuller example?
