### ISSUE TITLE
How can I do getGlobalSetting with useQueryProvider

### ISSUE THREAD

**Issue by lizy0329** [DamianOsipiuk/vue-query#98]
In my case: 
```javascript
app.vue
|- index.vue
|- fans-group.vue
```
**I use `useQueryProvider` in app.vue. But at the same time, I want get some setting from server acting on `index.vue` and `fans-group.vue`**

Once I useQuery in app.vue it told me `No queryClient found in Vue context, use 'useQueryProvider' to set one in the root component.`

```
// app.vue
useQueryProvider({
    defaultOptions: {
        queries: {
            staleTime: Infinity
        }
    }
});

const {data: settingData, isLoading: isLoadingSetting} = useQuery('getSetting', () =>
    getSetting({
        appCode: route.query.app_code
    })
);
// or
queryClient.prefetchQuery('getSetting', () =>
    getSetting({
        appCode: route.query.app_code
    })
);

```
What should i do?

**Comment by DamianOsipiuk** [comment]
Hi @lizy0329,

First question from me would be, which version of Vue are you using?
Cause v2 and v3 have a slightly different behavior and answer would be a little bit different.

Also where do you want to store this settings that you fetch from the server? Vuex store, Vue context?

**Comment by lizy0329** [comment]
I use vue 3.2.2

And then I will store the getSetting data to pinia, like vi_code

`index.vue` and `fans-group.vue` will get vi_code from pinia

**Comment by DamianOsipiuk** [comment]
So i guess there might be a problem when you use `useQueryProvider` and `useQuery` in the same component.
To solve that you might want to move `useQuery` to a child component or move logic of `useQueryProvider` to a plugin. Ex plugin (works only for vue 3):
```ts
import { VUE_QUERY_CLIENT, QueryClient } from 'vue-query';

export const vueQueryPlugin = {
  install: (app, options) => {
    const queryClient = new QueryClient(options);
    queryClient.mount();
    app.provide(VUE_QUERY_CLIENT, queryClient)
  }
}
```
