### ISSUE TITLE
QueryClient setQueryData updater old data is undefined

### ISSUE THREAD

**Issue by elliotsoomro** [DamianOsipiuk/vue-query#99]
Trying to use QueryClient's setQueryData method to update the cached data after a mutation with an updater function, the oldData param is undefined. Am I doing something wrong?

```js
import { useQuery, QueryClient } from 'vue-query'
import { folderResource } from '../apiroids/resources/folder.resource'
import { FolderDto } from '@shared/folder/dto/folder.dto'

const queryClient = new QueryClient()

const pageSize = ref(5)
const currentPage = ref(1)

const paginationParams = computed(() => ({
  skip: pageSize.value * (currentPage.value - 1),
  take: pageSize.value,
}))

const queryKey = reactive(['folders', { paginationParams }])

const { isLoading, data } = useQuery(
  queryKey,
  () => folderResource.getAll({
    queryParams: paginationParams.value,
  }),
  {
    keepPreviousData: true,
  },
)

const onFolderCreated = (newFolder: FolderDto) => {
  queryClient.setQueryData(queryKey, (oldData: any) => {
    console.log(oldData) // undefined
    return [...oldData, newFolder]
  })
}
```
A folder is created in a modal component:

```js
const { mutate: createFolder } = useMutation(
  () => folderResource.create(folder),
  {
    onSuccess: (data) => {
      emit('created', data.data)
      emit('update:show', false)
    },
  },
)

**Comment by lizy0329** [comment]
Does `paginationParams` has change that when you call the func `onFolderCreated `?

**Comment by DamianOsipiuk** [comment]
Hi @elliotsoomro,
I cannot spot any obvious error in your code snippet.

You could check few things though:
- if queryKey for `useQuery` and `setQueryData` are the same
- if initial query fails, or returns something unexpected, that could set data as undefined
- check in devtools what data is stored in cache and under which keys

If you still cannot spot the error, then maybe some minimal reproduction repo would help

**Comment by elliotsoomro** [comment]
The issue was with how I used the QueryClient. I was creating a new instance of it. Changing from 

```js
const queryClient = new QueryClient()
```

to this solved the issue:

```js
const queryClient = useQueryClient()
```

Thanks for your suggestions!
